ROOTDIR = ..
EXECUTABLE = subdivision
MAKE = make -f Makefile.nv
FILES = subdiv model splyload voutfloatN vout1dfloatN timing

#ATI PS2.0 FILES = loop model splyload voutfloatN vout1dfloatN timing
#nurbs subdivision 
LIBRARIES = $(RUNTIME_LIBS)
BRCCFLAGS = 
include $(ROOTDIR)/common.mk

