
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIX_clipmap__
#define __GLUX_GL_SGIX_clipmap__

GLUX_NEW_PLUGIN(GL_SGIX_clipmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_LINEAR_CLIPMAP_LINEAR_SGIX
#  define GL_LINEAR_CLIPMAP_LINEAR_SGIX 0x8170
#endif
#ifndef GL_TEXTURE_CLIPMAP_CENTER_SGIX
#  define GL_TEXTURE_CLIPMAP_CENTER_SGIX 0x8171
#endif
#ifndef GL_TEXTURE_CLIPMAP_FRAME_SGIX
#  define GL_TEXTURE_CLIPMAP_FRAME_SGIX 0x8172
#endif
#ifndef GL_TEXTURE_CLIPMAP_OFFSET_SGIX
#  define GL_TEXTURE_CLIPMAP_OFFSET_SGIX 0x8173
#endif
#ifndef GL_TEXTURE_CLIPMAP_VIRTUAL_DEPTH_SGIX
#  define GL_TEXTURE_CLIPMAP_VIRTUAL_DEPTH_SGIX 0x8174
#endif
#ifndef GL_TEXTURE_CLIPMAP_LOD_OFFSET_SGIX
#  define GL_TEXTURE_CLIPMAP_LOD_OFFSET_SGIX 0x8175
#endif
#ifndef GL_TEXTURE_CLIPMAP_DEPTH_SGIX
#  define GL_TEXTURE_CLIPMAP_DEPTH_SGIX 0x8176
#endif
#ifndef GL_MAX_CLIPMAP_DEPTH_SGIX
#  define GL_MAX_CLIPMAP_DEPTH_SGIX 0x8177
#endif
#ifndef GL_MAX_CLIPMAP_VIRTUAL_DEPTH_SGIX
#  define GL_MAX_CLIPMAP_VIRTUAL_DEPTH_SGIX 0x8178
#endif
#ifndef GL_NEAREST_CLIPMAP_NEAREST_SGIX
#  define GL_NEAREST_CLIPMAP_NEAREST_SGIX 0x844D
#endif
#ifndef GL_NEAREST_CLIPMAP_LINEAR_SGIX
#  define GL_NEAREST_CLIPMAP_LINEAR_SGIX 0x844E
#endif
#ifndef GL_LINEAR_CLIPMAP_NEAREST_SGIX
#  define GL_LINEAR_CLIPMAP_NEAREST_SGIX 0x844F
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
