
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ARB_texture_env_combine__
#define __GLUX_GL_ARB_texture_env_combine__

GLUX_NEW_PLUGIN(GL_ARB_texture_env_combine);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_COMBINE_ARB
#  define GL_COMBINE_ARB 0x8570
#endif
#ifndef GL_COMBINE_RGB_ARB
#  define GL_COMBINE_RGB_ARB 0x8571
#endif
#ifndef GL_COMBINE_ALPHA_ARB
#  define GL_COMBINE_ALPHA_ARB 0x8572
#endif
#ifndef GL_SOURCE0_RGB_ARB
#  define GL_SOURCE0_RGB_ARB 0x8580
#endif
#ifndef GL_SOURCE1_RGB_ARB
#  define GL_SOURCE1_RGB_ARB 0x8581
#endif
#ifndef GL_SOURCE2_RGB_ARB
#  define GL_SOURCE2_RGB_ARB 0x8582
#endif
#ifndef GL_SOURCE0_ALPHA_ARB
#  define GL_SOURCE0_ALPHA_ARB 0x8588
#endif
#ifndef GL_SOURCE1_ALPHA_ARB
#  define GL_SOURCE1_ALPHA_ARB 0x8589
#endif
#ifndef GL_SOURCE2_ALPHA_ARB
#  define GL_SOURCE2_ALPHA_ARB 0x858A
#endif
#ifndef GL_OPERAND0_RGB_ARB
#  define GL_OPERAND0_RGB_ARB 0x8590
#endif
#ifndef GL_OPERAND1_RGB_ARB
#  define GL_OPERAND1_RGB_ARB 0x8591
#endif
#ifndef GL_OPERAND2_RGB_ARB
#  define GL_OPERAND2_RGB_ARB 0x8592
#endif
#ifndef GL_OPERAND0_ALPHA_ARB
#  define GL_OPERAND0_ALPHA_ARB 0x8598
#endif
#ifndef GL_OPERAND1_ALPHA_ARB
#  define GL_OPERAND1_ALPHA_ARB 0x8599
#endif
#ifndef GL_OPERAND2_ALPHA_ARB
#  define GL_OPERAND2_ALPHA_ARB 0x859A
#endif
#ifndef GL_RGB_SCALE_ARB
#  define GL_RGB_SCALE_ARB 0x8573
#endif
#ifndef GL_ADD_SIGNED_ARB
#  define GL_ADD_SIGNED_ARB 0x8574
#endif
#ifndef GL_INTERPOLATE_ARB
#  define GL_INTERPOLATE_ARB 0x8575
#endif
#ifndef GL_SUBTRACT_ARB
#  define GL_SUBTRACT_ARB 0x84E7
#endif
#ifndef GL_CONSTANT_ARB
#  define GL_CONSTANT_ARB 0x8576
#endif
#ifndef GL_PRIMARY_COLOR_ARB
#  define GL_PRIMARY_COLOR_ARB 0x8577
#endif
#ifndef GL_PREVIOUS_ARB
#  define GL_PREVIOUS_ARB 0x8578
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
