// --------------------------------------------------------
#ifdef WIN32

// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:36 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_ARB_buffer_region__
#define __GLUX_WGL_ARB_buffer_region__

GLUX_NEW_PLUGIN(WGL_ARB_buffer_region);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef WGL_FRONT_COLOR_BUFFER_BIT_ARB
#  define WGL_FRONT_COLOR_BUFFER_BIT_ARB 0x00000001
#endif
#ifndef WGL_BACK_COLOR_BUFFER_BIT_ARB
#  define WGL_BACK_COLOR_BUFFER_BIT_ARB 0x00000002
#endif
#ifndef WGL_DEPTH_BUFFER_BIT_ARB
#  define WGL_DEPTH_BUFFER_BIT_ARB 0x00000004
#endif
#ifndef WGL_STENCIL_BUFFER_BIT_ARB
#  define WGL_STENCIL_BUFFER_BIT_ARB 0x00000008
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_wglCreateBufferRegionARB
typedef HANDLE (APIENTRYP PFNWGLUXCREATEBUFFERREGIONARBPROC) (HDC hDC, int iLayerPlane, UINT uType);
#endif
#ifndef __GLUX__GLFCT_wglDeleteBufferRegionARB
typedef VOID (APIENTRYP PFNWGLUXDELETEBUFFERREGIONARBPROC) (HANDLE hRegion);
#endif
#ifndef __GLUX__GLFCT_wglSaveBufferRegionARB
typedef BOOL (APIENTRYP PFNWGLUXSAVEBUFFERREGIONARBPROC) (HANDLE hRegion, int x, int y, int width, int height);
#endif
#ifndef __GLUX__GLFCT_wglRestoreBufferRegionARB
typedef BOOL (APIENTRYP PFNWGLUXRESTOREBUFFERREGIONARBPROC) (HANDLE hRegion, int x, int y, int width, int height, int xSrc, int ySrc);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_wglCreateBufferRegionARB
extern PFNWGLUXCREATEBUFFERREGIONARBPROC wglCreateBufferRegionARB;
#endif
#ifndef __GLUX__GLFCT_wglDeleteBufferRegionARB
extern PFNWGLUXDELETEBUFFERREGIONARBPROC wglDeleteBufferRegionARB;
#endif
#ifndef __GLUX__GLFCT_wglSaveBufferRegionARB
extern PFNWGLUXSAVEBUFFERREGIONARBPROC wglSaveBufferRegionARB;
#endif
#ifndef __GLUX__GLFCT_wglRestoreBufferRegionARB
extern PFNWGLUXRESTOREBUFFERREGIONARBPROC wglRestoreBufferRegionARB;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
