
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:34 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_texgen_emboss__
#define __GLUX_GL_NV_texgen_emboss__

GLUX_NEW_PLUGIN(GL_NV_texgen_emboss);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_EMBOSS_LIGHT_NV
#  define GL_EMBOSS_LIGHT_NV 0x855D
#endif
#ifndef GL_EMBOSS_CONSTANT_NV
#  define GL_EMBOSS_CONSTANT_NV 0x855E
#endif
#ifndef GL_EMBOSS_MAP_NV
#  define GL_EMBOSS_MAP_NV 0x855F
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
