// --------------------------------------------------------
#ifndef WIN32

// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:36 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GLX_EXT_visual_rating__
#define __GLUX_GLX_EXT_visual_rating__

GLUX_NEW_PLUGIN(GLX_EXT_visual_rating);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GLX_VISUAL_CAVEAT_EXT
#  define GLX_VISUAL_CAVEAT_EXT 0x20
#endif
#ifndef GLX_SLOW_VISUAL_EXT
#  define GLX_SLOW_VISUAL_EXT 0x8001
#endif
#ifndef GLX_NON_CONFORMANT_VISUAL_EXT
#  define GLX_NON_CONFORMANT_VISUAL_EXT 0x800D
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
