
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_convolution__
#define __GLUX_GL_EXT_convolution__

GLUX_NEW_PLUGIN(GL_EXT_convolution);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_CONVOLUTION_1D_EXT
#  define GL_CONVOLUTION_1D_EXT 0x8010
#endif
#ifndef GL_CONVOLUTION_2D_EXT
#  define GL_CONVOLUTION_2D_EXT 0x8011
#endif
#ifndef GL_SEPARABLE_2D_EXT
#  define GL_SEPARABLE_2D_EXT 0x8012
#endif
#ifndef GL_CONVOLUTION_BORDER_MODE_EXT
#  define GL_CONVOLUTION_BORDER_MODE_EXT 0x8013
#endif
#ifndef GL_CONVOLUTION_FILTER_SCALE_EXT
#  define GL_CONVOLUTION_FILTER_SCALE_EXT 0x8014
#endif
#ifndef GL_CONVOLUTION_FILTER_BIAS_EXT
#  define GL_CONVOLUTION_FILTER_BIAS_EXT 0x8015
#endif
#ifndef GL_REDUCE_EXT
#  define GL_REDUCE_EXT 0x8016
#endif
#ifndef GL_CONVOLUTION_FORMAT_EXT
#  define GL_CONVOLUTION_FORMAT_EXT 0x8017
#endif
#ifndef GL_CONVOLUTION_WIDTH_EXT
#  define GL_CONVOLUTION_WIDTH_EXT 0x8018
#endif
#ifndef GL_CONVOLUTION_HEIGHT_EXT
#  define GL_CONVOLUTION_HEIGHT_EXT 0x8019
#endif
#ifndef GL_MAX_CONVOLUTION_WIDTH_EXT
#  define GL_MAX_CONVOLUTION_WIDTH_EXT 0x801A
#endif
#ifndef GL_MAX_CONVOLUTION_HEIGHT_EXT
#  define GL_MAX_CONVOLUTION_HEIGHT_EXT 0x801B
#endif
#ifndef GL_POST_CONVOLUTION_RED_SCALE_EXT
#  define GL_POST_CONVOLUTION_RED_SCALE_EXT 0x801C
#endif
#ifndef GL_POST_CONVOLUTION_GREEN_SCALE_EXT
#  define GL_POST_CONVOLUTION_GREEN_SCALE_EXT 0x801D
#endif
#ifndef GL_POST_CONVOLUTION_BLUE_SCALE_EXT
#  define GL_POST_CONVOLUTION_BLUE_SCALE_EXT 0x801E
#endif
#ifndef GL_POST_CONVOLUTION_ALPHA_SCALE_EXT
#  define GL_POST_CONVOLUTION_ALPHA_SCALE_EXT 0x801F
#endif
#ifndef GL_POST_CONVOLUTION_RED_BIAS_EXT
#  define GL_POST_CONVOLUTION_RED_BIAS_EXT 0x8020
#endif
#ifndef GL_POST_CONVOLUTION_GREEN_BIAS_EXT
#  define GL_POST_CONVOLUTION_GREEN_BIAS_EXT 0x8021
#endif
#ifndef GL_POST_CONVOLUTION_BLUE_BIAS_EXT
#  define GL_POST_CONVOLUTION_BLUE_BIAS_EXT 0x8022
#endif
#ifndef GL_POST_CONVOLUTION_ALPHA_BIAS_EXT
#  define GL_POST_CONVOLUTION_ALPHA_BIAS_EXT 0x8023
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glConvolutionFilter1DEXT
typedef void (APIENTRYP PFNGLUXCONVOLUTIONFILTER1DEXTPROC) (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *image);
#endif
#ifndef __GLUX__GLFCT_glConvolutionFilter2DEXT
typedef void (APIENTRYP PFNGLUXCONVOLUTIONFILTER2DEXTPROC) (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *image);
#endif
#ifndef __GLUX__GLFCT_glConvolutionParameterfEXT
typedef void (APIENTRYP PFNGLUXCONVOLUTIONPARAMETERFEXTPROC) (GLenum target, GLenum pname, GLfloat params);
#endif
#ifndef __GLUX__GLFCT_glConvolutionParameterfvEXT
typedef void (APIENTRYP PFNGLUXCONVOLUTIONPARAMETERFVEXTPROC) (GLenum target, GLenum pname, const GLfloat *params);
#endif
#ifndef __GLUX__GLFCT_glConvolutionParameteriEXT
typedef void (APIENTRYP PFNGLUXCONVOLUTIONPARAMETERIEXTPROC) (GLenum target, GLenum pname, GLint params);
#endif
#ifndef __GLUX__GLFCT_glConvolutionParameterivEXT
typedef void (APIENTRYP PFNGLUXCONVOLUTIONPARAMETERIVEXTPROC) (GLenum target, GLenum pname, const GLint *params);
#endif
#ifndef __GLUX__GLFCT_glCopyConvolutionFilter1DEXT
typedef void (APIENTRYP PFNGLUXCOPYCONVOLUTIONFILTER1DEXTPROC) (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
#endif
#ifndef __GLUX__GLFCT_glCopyConvolutionFilter2DEXT
typedef void (APIENTRYP PFNGLUXCOPYCONVOLUTIONFILTER2DEXTPROC) (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height);
#endif
#ifndef __GLUX__GLFCT_glGetConvolutionFilterEXT
typedef void (APIENTRYP PFNGLUXGETCONVOLUTIONFILTEREXTPROC) (GLenum target, GLenum format, GLenum type, GLvoid *image);
#endif
#ifndef __GLUX__GLFCT_glGetConvolutionParameterfvEXT
typedef void (APIENTRYP PFNGLUXGETCONVOLUTIONPARAMETERFVEXTPROC) (GLenum target, GLenum pname, GLfloat *params);
#endif
#ifndef __GLUX__GLFCT_glGetConvolutionParameterivEXT
typedef void (APIENTRYP PFNGLUXGETCONVOLUTIONPARAMETERIVEXTPROC) (GLenum target, GLenum pname, GLint *params);
#endif
#ifndef __GLUX__GLFCT_glGetSeparableFilterEXT
typedef void (APIENTRYP PFNGLUXGETSEPARABLEFILTEREXTPROC) (GLenum target, GLenum format, GLenum type, GLvoid *row, GLvoid *column, GLvoid *span);
#endif
#ifndef __GLUX__GLFCT_glSeparableFilter2DEXT
typedef void (APIENTRYP PFNGLUXSEPARABLEFILTER2DEXTPROC) (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *row, const GLvoid *column);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glConvolutionFilter1DEXT
extern PFNGLUXCONVOLUTIONFILTER1DEXTPROC glConvolutionFilter1DEXT;
#endif
#ifndef __GLUX__GLFCT_glConvolutionFilter2DEXT
extern PFNGLUXCONVOLUTIONFILTER2DEXTPROC glConvolutionFilter2DEXT;
#endif
#ifndef __GLUX__GLFCT_glConvolutionParameterfEXT
extern PFNGLUXCONVOLUTIONPARAMETERFEXTPROC glConvolutionParameterfEXT;
#endif
#ifndef __GLUX__GLFCT_glConvolutionParameterfvEXT
extern PFNGLUXCONVOLUTIONPARAMETERFVEXTPROC glConvolutionParameterfvEXT;
#endif
#ifndef __GLUX__GLFCT_glConvolutionParameteriEXT
extern PFNGLUXCONVOLUTIONPARAMETERIEXTPROC glConvolutionParameteriEXT;
#endif
#ifndef __GLUX__GLFCT_glConvolutionParameterivEXT
extern PFNGLUXCONVOLUTIONPARAMETERIVEXTPROC glConvolutionParameterivEXT;
#endif
#ifndef __GLUX__GLFCT_glCopyConvolutionFilter1DEXT
extern PFNGLUXCOPYCONVOLUTIONFILTER1DEXTPROC glCopyConvolutionFilter1DEXT;
#endif
#ifndef __GLUX__GLFCT_glCopyConvolutionFilter2DEXT
extern PFNGLUXCOPYCONVOLUTIONFILTER2DEXTPROC glCopyConvolutionFilter2DEXT;
#endif
#ifndef __GLUX__GLFCT_glGetConvolutionFilterEXT
extern PFNGLUXGETCONVOLUTIONFILTEREXTPROC glGetConvolutionFilterEXT;
#endif
#ifndef __GLUX__GLFCT_glGetConvolutionParameterfvEXT
extern PFNGLUXGETCONVOLUTIONPARAMETERFVEXTPROC glGetConvolutionParameterfvEXT;
#endif
#ifndef __GLUX__GLFCT_glGetConvolutionParameterivEXT
extern PFNGLUXGETCONVOLUTIONPARAMETERIVEXTPROC glGetConvolutionParameterivEXT;
#endif
#ifndef __GLUX__GLFCT_glGetSeparableFilterEXT
extern PFNGLUXGETSEPARABLEFILTEREXTPROC glGetSeparableFilterEXT;
#endif
#ifndef __GLUX__GLFCT_glSeparableFilter2DEXT
extern PFNGLUXSEPARABLEFILTER2DEXTPROC glSeparableFilter2DEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
