
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:34 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ARB_depth_texture__
#define __GLUX_GL_ARB_depth_texture__

GLUX_NEW_PLUGIN(GL_ARB_depth_texture);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_DEPTH_COMPONENT16_ARB
#  define GL_DEPTH_COMPONENT16_ARB 0x81A5
#endif
#ifndef GL_DEPTH_COMPONENT24_ARB
#  define GL_DEPTH_COMPONENT24_ARB 0x81A6
#endif
#ifndef GL_DEPTH_COMPONENT32_ARB
#  define GL_DEPTH_COMPONENT32_ARB 0x81A7
#endif
#ifndef GL_TEXTURE_DEPTH_SIZE_ARB
#  define GL_TEXTURE_DEPTH_SIZE_ARB 0x884A
#endif
#ifndef GL_DEPTH_TEXTURE_MODE_ARB
#  define GL_DEPTH_TEXTURE_MODE_ARB 0x884B
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
