
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:34 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_float_buffer__
#define __GLUX_GL_NV_float_buffer__

GLUX_NEW_PLUGIN(GL_NV_float_buffer);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_FLOAT_R_NV
#  define GL_FLOAT_R_NV 0x8880
#endif
#ifndef GL_FLOAT_RG_NV
#  define GL_FLOAT_RG_NV 0x8881
#endif
#ifndef GL_FLOAT_RGB_NV
#  define GL_FLOAT_RGB_NV 0x8882
#endif
#ifndef GL_FLOAT_RGBA_NV
#  define GL_FLOAT_RGBA_NV 0x8883
#endif
#ifndef GL_FLOAT_R16_NV
#  define GL_FLOAT_R16_NV 0x8884
#endif
#ifndef GL_FLOAT_R32_NV
#  define GL_FLOAT_R32_NV 0x8885
#endif
#ifndef GL_FLOAT_RG16_NV
#  define GL_FLOAT_RG16_NV 0x8886
#endif
#ifndef GL_FLOAT_RG32_NV
#  define GL_FLOAT_RG32_NV 0x8887
#endif
#ifndef GL_FLOAT_RGB16_NV
#  define GL_FLOAT_RGB16_NV 0x8888
#endif
#ifndef GL_FLOAT_RGB32_NV
#  define GL_FLOAT_RGB32_NV 0x8889
#endif
#ifndef GL_FLOAT_RGBA16_NV
#  define GL_FLOAT_RGBA16_NV 0x888A
#endif
#ifndef GL_FLOAT_RGBA32_NV
#  define GL_FLOAT_RGBA32_NV 0x888B
#endif
#ifndef GL_TEXTURE_FLOAT_COMPONENTS_NV
#  define GL_TEXTURE_FLOAT_COMPONENTS_NV 0x888C
#endif
#ifndef GL_FLOAT_CLEAR_COLOR_VALUE_NV
#  define GL_FLOAT_CLEAR_COLOR_VALUE_NV 0x888D
#endif
#ifndef GL_FLOAT_RGBA_MODE_NV
#  define GL_FLOAT_RGBA_MODE_NV 0x888E
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
