
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:34 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIX_pixel_tiles__
#define __GLUX_GL_SGIX_pixel_tiles__

GLUX_NEW_PLUGIN(GL_SGIX_pixel_tiles);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_PIXEL_TILE_BEST_ALIGNMENT_SGIX
#  define GL_PIXEL_TILE_BEST_ALIGNMENT_SGIX 0x813E
#endif
#ifndef GL_PIXEL_TILE_CACHE_INCREMENT_SGIX
#  define GL_PIXEL_TILE_CACHE_INCREMENT_SGIX 0x813F
#endif
#ifndef GL_PIXEL_TILE_WIDTH_SGIX
#  define GL_PIXEL_TILE_WIDTH_SGIX 0x8140
#endif
#ifndef GL_PIXEL_TILE_HEIGHT_SGIX
#  define GL_PIXEL_TILE_HEIGHT_SGIX 0x8141
#endif
#ifndef GL_PIXEL_TILE_GRID_WIDTH_SGIX
#  define GL_PIXEL_TILE_GRID_WIDTH_SGIX 0x8142
#endif
#ifndef GL_PIXEL_TILE_GRID_HEIGHT_SGIX
#  define GL_PIXEL_TILE_GRID_HEIGHT_SGIX 0x8143
#endif
#ifndef GL_PIXEL_TILE_GRID_DEPTH_SGIX
#  define GL_PIXEL_TILE_GRID_DEPTH_SGIX 0x8144
#endif
#ifndef GL_PIXEL_TILE_CACHE_SIZE_SGIX
#  define GL_PIXEL_TILE_CACHE_SIZE_SGIX 0x8145
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
