// --------------------------------------------------------
// Generated by glux perl script ()
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifndef __GLUX_LOAD_ALL__
#define __GLUX_LOAD_ALL__
// --------------------------------------------------------
#include <glux.h>
// --------------------------------------------------------
 GLUX_LOAD(GL_NV_fence);
 GLUX_LOAD(GL_SGIX_sprite);
#ifndef WIN32
 GLUX_LOAD(GLX_MESA_release_buffers);
#endif
 GLUX_LOAD(GL_ATI_text_fragment_shader);
 GLUX_LOAD(GL_EXT_compiled_vertex_array);
 GLUX_LOAD(GL_EXT_vertex_shader);
 GLUX_LOAD(GL_EXT_texture_lod_bias);
 GLUX_LOAD(GL_APPLE_element_array);
 GLUX_LOAD(GL_NV_texgen_reflection);
#ifndef WIN32
 GLUX_LOAD(GLX_MESA_pixmap_colormap);
#endif
 GLUX_LOAD(GL_EXT_multisample);
 GLUX_LOAD(GL_ARB_matrix_palette);
 GLUX_LOAD(GL_EXT_cull_vertex);
 GLUX_LOAD(GL_SGIX_instruments);
 GLUX_LOAD(GL_EXT_texture_env_add);
 GLUX_LOAD(GL_NV_texture_shader2);
 GLUX_LOAD(GL_EXT_draw_range_elements);
 GLUX_LOAD(GL_NV_light_max_exponent);
 GLUX_LOAD(GL_SGIS_texture_color_mask);
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_make_current_read);
#endif
 GLUX_LOAD(GL_EXT_paletted_texture);
 GLUX_LOAD(GL_IBM_cull_vertex);
#ifdef WIN32
 GLUX_LOAD(WGL_NV_render_depth_texture);
#endif
 GLUX_LOAD(GL_ATI_texture_float);
#ifndef WIN32
 GLUX_LOAD(GLX_OML_swap_method);
#endif
 GLUX_LOAD(GL_NV_texture_env_combine4);
 GLUX_LOAD(GL_EXT_cmyka);
 GLUX_LOAD(GL_APPLE_vertex_array_object);
 GLUX_LOAD(GL_EXT_422_pixels);
 GLUX_LOAD(GL_NV_register_combiners2);
 GLUX_LOAD(GL_ARB_texture_env_crossbar);
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_extensions_string);
#endif
 GLUX_LOAD(GL_SGIX_ycrcba);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIX_pbuffer);
#endif
 GLUX_LOAD(GL_ATI_draw_buffers);
 GLUX_LOAD(GL_INTEL_parallel_arrays);
 GLUX_LOAD(GL_NV_occlusion_query);
 GLUX_LOAD(GL_NV_multisample_filter_hint);
 GLUX_LOAD(GL_EXT_pixel_transform_color_table);
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_extensions_string);
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_gamma);
#endif
 GLUX_LOAD(GL_SGIX_subsample);
 GLUX_LOAD(GL_SGIX_texture_coordinate_clamp);
 GLUX_LOAD(GL_NV_texture_shader);
 GLUX_LOAD(GL_EXT_vertex_array);
 GLUX_LOAD(GL_EXT_depth_bounds_test);
 GLUX_LOAD(GL_EXT_vertex_weighting);
#ifdef WIN32
 GLUX_LOAD(WGL_OML_sync_control);
#endif
 GLUX_LOAD(GL_SGIX_scalebias_hint);
 GLUX_LOAD(GL_ARB_point_parameters);
 GLUX_LOAD(GL_SGIX_shadow);
 GLUX_LOAD(GL_SUN_convolution_border_modes);
 GLUX_LOAD(GL_ATI_texture_mirror_once);
#ifdef WIN32
 GLUX_LOAD(WGL_NV_vertex_array_range);
#endif
 GLUX_LOAD(GL_EXT_stencil_two_side);
 GLUX_LOAD(GL_ATI_fragment_shader);
 GLUX_LOAD(GL_EXT_texture_filter_anisotropic);
#ifdef WIN32
 GLUX_LOAD(WGL_NV_float_buffer);
#endif
 GLUX_LOAD(GL_SGIX_ycrcb_subsample);
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_multisample);
#endif
 GLUX_LOAD(GL_SGIS_texture_edge_clamp);
 GLUX_LOAD(GL_APPLE_fence);
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_pbuffer);
#endif
 GLUX_LOAD(GL_EXT_shared_texture_palette);
 GLUX_LOAD(GL_INTEL_texture_scissor);
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_genlock);
#endif
 GLUX_LOAD(GL_INGR_blend_func_separate);
 GLUX_LOAD(GL_ATI_vertex_attrib_array_object);
 GLUX_LOAD(GL_ARB_multitexture);
 GLUX_LOAD(GL_APPLE_client_storage);
 GLUX_LOAD(GL_REND_screen_coordinates);
 GLUX_LOAD(GL_EXT_multi_draw_arrays);
#ifndef WIN32
 GLUX_LOAD(GLX_EXT_import_context);
#endif
 GLUX_LOAD(GL_SGIX_texture_select);
 GLUX_LOAD(GL_SUNX_constant_data);
 GLUX_LOAD(GL_OML_resample);
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_swap_control);
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_digital_video_control);
#endif
 GLUX_LOAD(GL_EXT_copy_texture);
 GLUX_LOAD(GL_EXT_rescale_normal);
 GLUX_LOAD(GL_EXT_bgra);
 GLUX_LOAD(GL_EXT_polygon_offset);
 GLUX_LOAD(GL_NV_fragment_program);
 GLUX_LOAD(GL_SGIS_generate_mipmap);
 GLUX_LOAD(GL_EXT_histogram);
#ifndef WIN32
 GLUX_LOAD(GLX_3DFX_multisample);
#endif
#ifndef WIN32
 GLUX_LOAD(GLX_MESA_set_3dfx_mode);
#endif
 GLUX_LOAD(GL_APPLE_ycbcr_422);
#ifndef WIN32
 GLUX_LOAD(GLX_SGI_cushion);
#endif
 GLUX_LOAD(GL_ARB_texture_cube_map);
 GLUX_LOAD(GL_EXT_pixel_transform);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIX_visual_select_group);
#endif
 GLUX_LOAD(GL_NV_blend_square);
 GLUX_LOAD(GL_NV_copy_depth_to_color);
 GLUX_LOAD(GL_ARB_transpose_matrix);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIX_fbconfig);
#endif
 GLUX_LOAD(GL_OML_subsample);
 GLUX_LOAD(GL_MESA_pack_invert);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIS_blended_overlay);
#endif
 GLUX_LOAD(GL_INGR_interlace_read);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIX_video_resize);
#endif
 GLUX_LOAD(GL_SGIX_calligraphic_fragment);
 GLUX_LOAD(GL_SGIX_tag_sample_buffer);
 GLUX_LOAD(GL_EXT_blend_equation_separate);
 GLUX_LOAD(GL_SGIX_list_priority);
 GLUX_LOAD(GL_ATI_envmap_bumpmap);
 GLUX_LOAD(GL_SGIX_texture_add_env);
#ifndef WIN32
 GLUX_LOAD(GLX_ARB_get_proc_address);
#endif
#ifndef WIN32
 GLUX_LOAD(GLX_SGI_make_current_read);
#endif
 GLUX_LOAD(GL_3DFX_tbuffer);
 GLUX_LOAD(GL_EXT_index_array_formats);
 GLUX_LOAD(GL_EXT_convolution);
 GLUX_LOAD(GL_SGIS_sharpen_texture);
 GLUX_LOAD(GL_EXT_index_material);
 GLUX_LOAD(GL_SGIX_vertex_preclip);
 GLUX_LOAD(GL_EXT_blend_color);
 GLUX_LOAD(GL_NV_texture_expand_normal);
#ifdef WIN32
 GLUX_LOAD(WGL_NV_render_texture_rectangle);
#endif
 GLUX_LOAD(GL_APPLE_vertex_array_range);
 GLUX_LOAD(GL_EXT_misc_attribute);
 GLUX_LOAD(GL_ARB_point_sprite);
 GLUX_LOAD(GL_WIN_specular_fog);
 GLUX_LOAD(GL_NV_point_sprite);
 GLUX_LOAD(GL_SGIS_detail_texture);
 GLUX_LOAD(GL_EXT_texture3D);
 GLUX_LOAD(GL_SGIX_pixel_texture);
 GLUX_LOAD(GL_SGIX_texture_lod_bias);
 GLUX_LOAD(GL_INGR_palette_buffer);
 GLUX_LOAD(GL_NV_vertex_program1_1);
 GLUX_LOAD(GL_SGIX_fog_offset);
 GLUX_LOAD(GL_SGIX_pixel_tiles);
 GLUX_LOAD(GL_NV_depth_clamp);
 GLUX_LOAD(GL_SGIS_texture_select);
 GLUX_LOAD(GL_NV_texgen_emboss);
 GLUX_LOAD(GL_3DFX_multisample);
 GLUX_LOAD(GL_SUN_vertex);
 GLUX_LOAD(GL_ARB_vertex_program);
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_multisample);
#endif
 GLUX_LOAD(GL_ARB_shadow_ambient);
 GLUX_LOAD(GL_SGIX_texture_scale_bias);
 GLUX_LOAD(GL_PGI_vertex_hints);
 GLUX_LOAD(GL_APPLE_transform_hint);
 GLUX_LOAD(GL_SGIX_depth_texture);
 GLUX_LOAD(GL_EXT_index_texture);
 GLUX_LOAD(GL_ARB_depth_texture);
#ifndef WIN32
 GLUX_LOAD(GLX_MESA_copy_sub_buffer);
#endif
 GLUX_LOAD(GL_EXT_color_matrix);
 GLUX_LOAD(GL_HP_image_transform);
 GLUX_LOAD(GL_SGIX_blend_alpha_minmax);
 GLUX_LOAD(GL_SGIX_depth_pass_instrument);
 GLUX_LOAD(GL_ARB_fragment_shader);
 GLUX_LOAD(GL_SGIS_multisample);
 GLUX_LOAD(GL_SGIX_flush_raster);
 GLUX_LOAD(GL_S3_s3tc);
 GLUX_LOAD(GL_ARB_texture_env_dot3);
 GLUX_LOAD(GL_NV_texture_compression_vtc);
 GLUX_LOAD(GL_ATI_element_array);
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_swap_frame_lock);
#endif
 GLUX_LOAD(GL_EXT_abgr);
 GLUX_LOAD(GL_MESA_window_pos);
 GLUX_LOAD(GL_EXT_texture_compression_s3tc);
 GLUX_LOAD(GL_SGIX_shadow_ambient);
 GLUX_LOAD(GL_EXT_separate_specular_color);
 GLUX_LOAD(GL_NV_evaluators);
 GLUX_LOAD(GL_SGIX_framezoom);
 GLUX_LOAD(GL_SUN_global_alpha);
 GLUX_LOAD(GL_SGIX_async_pixel);
 GLUX_LOAD(GL_EXT_index_func);
 GLUX_LOAD(GL_ARB_vertex_shader);
 GLUX_LOAD(GL_HP_occlusion_test);
 GLUX_LOAD(GL_EXT_texture_mirror_clamp);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIX_swap_barrier);
#endif
 GLUX_LOAD(GL_EXT_texture_env_combine);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIS_shared_multisample);
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_render_texture);
#endif
 GLUX_LOAD(GL_SGIX_convolution_accuracy);
 GLUX_LOAD(GL_MESA_ycbcr_texture);
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_pixel_format);
#endif
 GLUX_LOAD(GL_ARB_texture_mirrored_repeat);
 GLUX_LOAD(GL_OML_interlace);
 GLUX_LOAD(GL_ARB_texture_compression);
 GLUX_LOAD(GL_ARB_texture_non_power_of_two);
 GLUX_LOAD(GL_ARB_vertex_buffer_object);
 GLUX_LOAD(GL_NV_vertex_program2);
 GLUX_LOAD(GL_EXT_fog_coord);
#ifndef WIN32
 GLUX_LOAD(GLX_OML_sync_control);
#endif
 GLUX_LOAD(GL_SGIX_fog_scale);
 GLUX_LOAD(GL_EXT_texture_cube_map);
 GLUX_LOAD(GL_ATI_vertex_array_object);
 GLUX_LOAD(GL_EXT_blend_subtract);
 GLUX_LOAD(GL_SGIX_impact_pixel_texture);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIS_multisample);
#endif
 GLUX_LOAD(GL_EXT_texture_object);
 GLUX_LOAD(GL_NV_fog_distance);
 GLUX_LOAD(GL_NV_half_float);
 GLUX_LOAD(GL_EXT_color_subtable);
 GLUX_LOAD(GL_NV_packed_depth_stencil);
 GLUX_LOAD(GL_NV_float_buffer);
#ifndef WIN32
 GLUX_LOAD(GLX_SUN_get_transparent_index);
#endif
 GLUX_LOAD(GL_SGIX_igloo_interface);
 GLUX_LOAD(GL_IBM_multimode_draw_arrays);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIX_video_source);
#endif
 GLUX_LOAD(GL_EXT_texture_perturb_normal);
 GLUX_LOAD(GL_ARB_texture_env_add);
 GLUX_LOAD(GL_ARB_occlusion_query);
#ifndef WIN32
 GLUX_LOAD(GLX_EXT_visual_info);
#endif
#ifndef WIN32
 GLUX_LOAD(GLX_ARB_multisample);
#endif
 GLUX_LOAD(GL_EXT_stencil_wrap);
 GLUX_LOAD(GL_SUN_slice_accum);
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_depth_float);
#endif
 GLUX_LOAD(GL_ATI_texture_env_combine3);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIX_swap_group);
#endif
 GLUX_LOAD(GL_EXT_secondary_color);
 GLUX_LOAD(GL_SGIX_clipmap);
 GLUX_LOAD(GL_SGIX_ycrcb);
 GLUX_LOAD(GL_NV_register_combiners);
 GLUX_LOAD(GL_SUN_mesh_array);
 GLUX_LOAD(GL_EXT_shadow_funcs);
 GLUX_LOAD(GL_EXT_texture);
 GLUX_LOAD(GL_ARB_multisample);
 GLUX_LOAD(GL_ARB_window_pos);
#ifndef WIN32
 GLUX_LOAD(GLX_SGIX_dmbuffer);
#endif
 GLUX_LOAD(GL_SGIS_point_parameters);
 GLUX_LOAD(GL_SGI_color_matrix);
 GLUX_LOAD(GL_SGIX_texture_multi_buffer);
 GLUX_LOAD(GL_EXT_blend_logic_op);
 GLUX_LOAD(GL_WIN_phong_shading);
 GLUX_LOAD(GL_IBM_texture_mirrored_repeat);
 GLUX_LOAD(GL_SGIX_reference_plane);
 GLUX_LOAD(GL_APPLE_specular_vector);
 GLUX_LOAD(GL_NV_texture_rectangle);
 GLUX_LOAD(GL_ARB_fragment_program);
 GLUX_LOAD(GL_3DFX_texture_compression_FXT1);
 GLUX_LOAD(GL_ATI_separate_stencil);
 GLUX_LOAD(GL_EXT_coordinate_frame);
 GLUX_LOAD(GL_EXT_blend_minmax);
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_pbuffer);
#endif
 GLUX_LOAD(GL_EXT_point_parameters);
 GLUX_LOAD(GL_IBM_rasterpos_clip);
 GLUX_LOAD(GL_EXT_packed_pixels);
 GLUX_LOAD(GL_MESA_resize_buffers);
 GLUX_LOAD(GL_NV_vertex_array_range2);
 GLUX_LOAD(GL_SGI_color_table);
 GLUX_LOAD(GL_ARB_texture_border_clamp);
 GLUX_LOAD(GL_ARB_vertex_blend);
 GLUX_LOAD(GL_ARB_texture_env_combine);
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_display_color_table);
#endif
 GLUX_LOAD(GL_SGIX_fragment_lighting);
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_swap_frame_usage);
#endif
 GLUX_LOAD(GL_ARB_fragment_program_shadow);
 GLUX_LOAD(GL_NV_vertex_program);
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_pixel_format);
#endif
 GLUX_LOAD(GL_PGI_misc_hints);
 GLUX_LOAD(GL_SGIS_texture_filter4);
 GLUX_LOAD(GL_SGIX_interlace);
 GLUX_LOAD(GL_SGIX_resample);
#ifndef WIN32
 GLUX_LOAD(GLX_SGI_video_sync);
#endif
 GLUX_LOAD(GL_EXT_subtexture);
 GLUX_LOAD(GL_HP_convolution_border_modes);
 GLUX_LOAD(GL_ATI_vertex_streams);
 GLUX_LOAD(GL_SGIS_point_line_texgen);
 GLUX_LOAD(GL_ARB_shader_objects);
 GLUX_LOAD(GL_SUN_triangle_list);
 GLUX_LOAD(GL_EXT_light_texture);
 GLUX_LOAD(GL_NV_primitive_restart);
#ifndef WIN32
 GLUX_LOAD(GLX_SGI_swap_control);
#endif
 GLUX_LOAD(GL_IBM_vertex_array_lists);
 GLUX_LOAD(GL_HP_texture_lighting);
 GLUX_LOAD(GL_SGIX_async_histogram);
 GLUX_LOAD(GL_EXT_clip_volume_hint);
 GLUX_LOAD(GL_SGIS_fog_function);
 GLUX_LOAD(GL_INGR_color_clamp);
 GLUX_LOAD(GL_SGI_texture_color_table);
 GLUX_LOAD(GL_EXT_blend_func_separate);
 GLUX_LOAD(GL_SGIS_pixel_texture);
 GLUX_LOAD(GL_SGIX_async);
 GLUX_LOAD(GL_SGIS_texture_lod);
 GLUX_LOAD(GL_ARB_shadow);
#ifdef WIN32
 GLUX_LOAD(WGL_3DFX_multisample);
#endif
 GLUX_LOAD(GL_NV_texture_shader3);
 GLUX_LOAD(GL_SGI_depth_pass_instrument);
 GLUX_LOAD(GL_EXT_texture_env_dot3);
 GLUX_LOAD(GL_SGIX_ir_instrument1);
 GLUX_LOAD(GL_ATI_pn_triangles);
 GLUX_LOAD(GL_SGIS_texture_border_clamp);
 GLUX_LOAD(GL_NV_vertex_array_range);
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_buffer_region);
#endif
 GLUX_LOAD(GL_ARB_shading_language_100);
 GLUX_LOAD(GL_SGIX_polynomial_ffd);
 GLUX_LOAD(GL_ARB_imaging);
#ifndef WIN32
 GLUX_LOAD(GLX_EXT_visual_rating);
#endif
 GLUX_LOAD(GL_NV_pixel_data_range);
 GLUX_LOAD(GL_SGIS_texture4D);
 GLUX_LOAD(GL_ATI_map_object_buffer);
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_make_current_read);
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_image_buffer);
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
