
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_HP_convolution_border_modes__
#define __GLUX_GL_HP_convolution_border_modes__

GLUX_NEW_PLUGIN(GL_HP_convolution_border_modes);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_IGNORE_BORDER_HP
#  define GL_IGNORE_BORDER_HP 0x8150
#endif
#ifndef GL_CONSTANT_BORDER_HP
#  define GL_CONSTANT_BORDER_HP 0x8151
#endif
#ifndef GL_REPLICATE_BORDER_HP
#  define GL_REPLICATE_BORDER_HP 0x8153
#endif
#ifndef GL_CONVOLUTION_BORDER_COLOR_HP
#  define GL_CONVOLUTION_BORDER_COLOR_HP 0x8154
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
