
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:34 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIX_depth_texture__
#define __GLUX_GL_SGIX_depth_texture__

GLUX_NEW_PLUGIN(GL_SGIX_depth_texture);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_DEPTH_COMPONENT16_SGIX
#  define GL_DEPTH_COMPONENT16_SGIX 0x81A5
#endif
#ifndef GL_DEPTH_COMPONENT24_SGIX
#  define GL_DEPTH_COMPONENT24_SGIX 0x81A6
#endif
#ifndef GL_DEPTH_COMPONENT32_SGIX
#  define GL_DEPTH_COMPONENT32_SGIX 0x81A7
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
