
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_fence__
#define __GLUX_GL_APPLE_fence__

GLUX_NEW_PLUGIN(GL_APPLE_fence);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_DRAW_PIXELS_APPLE
#  define GL_DRAW_PIXELS_APPLE 0x8A0A
#endif
#ifndef GL_FENCE_APPLE
#  define GL_FENCE_APPLE 0x8A0B
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glGenFencesAPPLE
typedef void (APIENTRYP PFNGLUXGENFENCESAPPLEPROC) (GLsizei n, GLuint *fences);
#endif
#ifndef __GLUX__GLFCT_glDeleteFencesAPPLE
typedef void (APIENTRYP PFNGLUXDELETEFENCESAPPLEPROC) (GLsizei n, const GLuint *fences);
#endif
#ifndef __GLUX__GLFCT_glSetFenceAPPLE
typedef void (APIENTRYP PFNGLUXSETFENCEAPPLEPROC) (GLuint fence);
#endif
#ifndef __GLUX__GLFCT_glIsFenceAPPLE
typedef GLboolean (APIENTRYP PFNGLUXISFENCEAPPLEPROC) (GLuint fence);
#endif
#ifndef __GLUX__GLFCT_glTestFenceAPPLE
typedef GLboolean (APIENTRYP PFNGLUXTESTFENCEAPPLEPROC) (GLuint fence);
#endif
#ifndef __GLUX__GLFCT_glFinishFenceAPPLE
typedef void (APIENTRYP PFNGLUXFINISHFENCEAPPLEPROC) (GLuint fence);
#endif
#ifndef __GLUX__GLFCT_glTestObjectAPPLE
typedef GLboolean (APIENTRYP PFNGLUXTESTOBJECTAPPLEPROC) (GLenum object, GLuint name);
#endif
#ifndef __GLUX__GLFCT_glFinishObjectAPPLE
typedef void (APIENTRYP PFNGLUXFINISHOBJECTAPPLEPROC) (GLenum object, GLint name);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glGenFencesAPPLE
extern PFNGLUXGENFENCESAPPLEPROC glGenFencesAPPLE;
#endif
#ifndef __GLUX__GLFCT_glDeleteFencesAPPLE
extern PFNGLUXDELETEFENCESAPPLEPROC glDeleteFencesAPPLE;
#endif
#ifndef __GLUX__GLFCT_glSetFenceAPPLE
extern PFNGLUXSETFENCEAPPLEPROC glSetFenceAPPLE;
#endif
#ifndef __GLUX__GLFCT_glIsFenceAPPLE
extern PFNGLUXISFENCEAPPLEPROC glIsFenceAPPLE;
#endif
#ifndef __GLUX__GLFCT_glTestFenceAPPLE
extern PFNGLUXTESTFENCEAPPLEPROC glTestFenceAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFinishFenceAPPLE
extern PFNGLUXFINISHFENCEAPPLEPROC glFinishFenceAPPLE;
#endif
#ifndef __GLUX__GLFCT_glTestObjectAPPLE
extern PFNGLUXTESTOBJECTAPPLEPROC glTestObjectAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFinishObjectAPPLE
extern PFNGLUXFINISHOBJECTAPPLEPROC glFinishObjectAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
