// --------------------------------------------------------
#ifndef WIN32

// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:34 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GLX_SGIS_shared_multisample__
#define __GLUX_GLX_SGIS_shared_multisample__

GLUX_NEW_PLUGIN(GLX_SGIS_shared_multisample);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GLX_MULTISAMPLE_SUB_RECT_WIDTH_SGIS
#  define GLX_MULTISAMPLE_SUB_RECT_WIDTH_SGIS 0x8026
#endif
#ifndef GLX_MULTISAMPLE_SUB_RECT_HEIGHT_SGIS
#  define GLX_MULTISAMPLE_SUB_RECT_HEIGHT_SGIS 0x8027
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
