
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_texture_shader__
#define __GLUX_GL_NV_texture_shader__

GLUX_NEW_PLUGIN(GL_NV_texture_shader);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_OFFSET_TEXTURE_RECTANGLE_NV
#  define GL_OFFSET_TEXTURE_RECTANGLE_NV 0x864C
#endif
#ifndef GL_OFFSET_TEXTURE_RECTANGLE_SCALE_NV
#  define GL_OFFSET_TEXTURE_RECTANGLE_SCALE_NV 0x864D
#endif
#ifndef GL_DOT_PRODUCT_TEXTURE_RECTANGLE_NV
#  define GL_DOT_PRODUCT_TEXTURE_RECTANGLE_NV 0x864E
#endif
#ifndef GL_RGBA_UNSIGNED_DOT_PRODUCT_MAPPING_NV
#  define GL_RGBA_UNSIGNED_DOT_PRODUCT_MAPPING_NV 0x86D9
#endif
#ifndef GL_UNSIGNED_INT_S8_S8_8_8_NV
#  define GL_UNSIGNED_INT_S8_S8_8_8_NV 0x86DA
#endif
#ifndef GL_UNSIGNED_INT_8_8_S8_S8_REV_NV
#  define GL_UNSIGNED_INT_8_8_S8_S8_REV_NV 0x86DB
#endif
#ifndef GL_DSDT_MAG_INTENSITY_NV
#  define GL_DSDT_MAG_INTENSITY_NV 0x86DC
#endif
#ifndef GL_SHADER_CONSISTENT_NV
#  define GL_SHADER_CONSISTENT_NV 0x86DD
#endif
#ifndef GL_TEXTURE_SHADER_NV
#  define GL_TEXTURE_SHADER_NV 0x86DE
#endif
#ifndef GL_SHADER_OPERATION_NV
#  define GL_SHADER_OPERATION_NV 0x86DF
#endif
#ifndef GL_CULL_MODES_NV
#  define GL_CULL_MODES_NV 0x86E0
#endif
#ifndef GL_OFFSET_TEXTURE_MATRIX_NV
#  define GL_OFFSET_TEXTURE_MATRIX_NV 0x86E1
#endif
#ifndef GL_OFFSET_TEXTURE_SCALE_NV
#  define GL_OFFSET_TEXTURE_SCALE_NV 0x86E2
#endif
#ifndef GL_OFFSET_TEXTURE_BIAS_NV
#  define GL_OFFSET_TEXTURE_BIAS_NV 0x86E3
#endif
#ifndef GL_OFFSET_TEXTURE_2D_MATRIX_NV
#  define GL_OFFSET_TEXTURE_2D_MATRIX_NV GL_OFFSET_TEXTURE_MATRIX_NV
#endif
#ifndef GL_OFFSET_TEXTURE_2D_SCALE_NV
#  define GL_OFFSET_TEXTURE_2D_SCALE_NV GL_OFFSET_TEXTURE_SCALE_NV
#endif
#ifndef GL_OFFSET_TEXTURE_2D_BIAS_NV
#  define GL_OFFSET_TEXTURE_2D_BIAS_NV GL_OFFSET_TEXTURE_BIAS_NV
#endif
#ifndef GL_PREVIOUS_TEXTURE_INPUT_NV
#  define GL_PREVIOUS_TEXTURE_INPUT_NV 0x86E4
#endif
#ifndef GL_CONST_EYE_NV
#  define GL_CONST_EYE_NV 0x86E5
#endif
#ifndef GL_PASS_THROUGH_NV
#  define GL_PASS_THROUGH_NV 0x86E6
#endif
#ifndef GL_CULL_FRAGMENT_NV
#  define GL_CULL_FRAGMENT_NV 0x86E7
#endif
#ifndef GL_OFFSET_TEXTURE_2D_NV
#  define GL_OFFSET_TEXTURE_2D_NV 0x86E8
#endif
#ifndef GL_DEPENDENT_AR_TEXTURE_2D_NV
#  define GL_DEPENDENT_AR_TEXTURE_2D_NV 0x86E9
#endif
#ifndef GL_DEPENDENT_GB_TEXTURE_2D_NV
#  define GL_DEPENDENT_GB_TEXTURE_2D_NV 0x86EA
#endif
#ifndef GL_DOT_PRODUCT_NV
#  define GL_DOT_PRODUCT_NV 0x86EC
#endif
#ifndef GL_DOT_PRODUCT_DEPTH_REPLACE_NV
#  define GL_DOT_PRODUCT_DEPTH_REPLACE_NV 0x86ED
#endif
#ifndef GL_DOT_PRODUCT_TEXTURE_2D_NV
#  define GL_DOT_PRODUCT_TEXTURE_2D_NV 0x86EE
#endif
#ifndef GL_DOT_PRODUCT_TEXTURE_CUBE_MAP_NV
#  define GL_DOT_PRODUCT_TEXTURE_CUBE_MAP_NV 0x86F0
#endif
#ifndef GL_DOT_PRODUCT_DIFFUSE_CUBE_MAP_NV
#  define GL_DOT_PRODUCT_DIFFUSE_CUBE_MAP_NV 0x86F1
#endif
#ifndef GL_DOT_PRODUCT_REFLECT_CUBE_MAP_NV
#  define GL_DOT_PRODUCT_REFLECT_CUBE_MAP_NV 0x86F2
#endif
#ifndef GL_DOT_PRODUCT_CONST_EYE_REFLECT_CUBE_MAP_NV
#  define GL_DOT_PRODUCT_CONST_EYE_REFLECT_CUBE_MAP_NV 0x86F3
#endif
#ifndef GL_HILO_NV
#  define GL_HILO_NV 0x86F4
#endif
#ifndef GL_DSDT_NV
#  define GL_DSDT_NV 0x86F5
#endif
#ifndef GL_DSDT_MAG_NV
#  define GL_DSDT_MAG_NV 0x86F6
#endif
#ifndef GL_DSDT_MAG_VIB_NV
#  define GL_DSDT_MAG_VIB_NV 0x86F7
#endif
#ifndef GL_HILO16_NV
#  define GL_HILO16_NV 0x86F8
#endif
#ifndef GL_SIGNED_HILO_NV
#  define GL_SIGNED_HILO_NV 0x86F9
#endif
#ifndef GL_SIGNED_HILO16_NV
#  define GL_SIGNED_HILO16_NV 0x86FA
#endif
#ifndef GL_SIGNED_RGBA_NV
#  define GL_SIGNED_RGBA_NV 0x86FB
#endif
#ifndef GL_SIGNED_RGBA8_NV
#  define GL_SIGNED_RGBA8_NV 0x86FC
#endif
#ifndef GL_SIGNED_RGB_NV
#  define GL_SIGNED_RGB_NV 0x86FE
#endif
#ifndef GL_SIGNED_RGB8_NV
#  define GL_SIGNED_RGB8_NV 0x86FF
#endif
#ifndef GL_SIGNED_LUMINANCE_NV
#  define GL_SIGNED_LUMINANCE_NV 0x8701
#endif
#ifndef GL_SIGNED_LUMINANCE8_NV
#  define GL_SIGNED_LUMINANCE8_NV 0x8702
#endif
#ifndef GL_SIGNED_LUMINANCE_ALPHA_NV
#  define GL_SIGNED_LUMINANCE_ALPHA_NV 0x8703
#endif
#ifndef GL_SIGNED_LUMINANCE8_ALPHA8_NV
#  define GL_SIGNED_LUMINANCE8_ALPHA8_NV 0x8704
#endif
#ifndef GL_SIGNED_ALPHA_NV
#  define GL_SIGNED_ALPHA_NV 0x8705
#endif
#ifndef GL_SIGNED_ALPHA8_NV
#  define GL_SIGNED_ALPHA8_NV 0x8706
#endif
#ifndef GL_SIGNED_INTENSITY_NV
#  define GL_SIGNED_INTENSITY_NV 0x8707
#endif
#ifndef GL_SIGNED_INTENSITY8_NV
#  define GL_SIGNED_INTENSITY8_NV 0x8708
#endif
#ifndef GL_DSDT8_NV
#  define GL_DSDT8_NV 0x8709
#endif
#ifndef GL_DSDT8_MAG8_NV
#  define GL_DSDT8_MAG8_NV 0x870A
#endif
#ifndef GL_DSDT8_MAG8_INTENSITY8_NV
#  define GL_DSDT8_MAG8_INTENSITY8_NV 0x870B
#endif
#ifndef GL_SIGNED_RGB_UNSIGNED_ALPHA_NV
#  define GL_SIGNED_RGB_UNSIGNED_ALPHA_NV 0x870C
#endif
#ifndef GL_SIGNED_RGB8_UNSIGNED_ALPHA8_NV
#  define GL_SIGNED_RGB8_UNSIGNED_ALPHA8_NV 0x870D
#endif
#ifndef GL_HI_SCALE_NV
#  define GL_HI_SCALE_NV 0x870E
#endif
#ifndef GL_LO_SCALE_NV
#  define GL_LO_SCALE_NV 0x870F
#endif
#ifndef GL_DS_SCALE_NV
#  define GL_DS_SCALE_NV 0x8710
#endif
#ifndef GL_DT_SCALE_NV
#  define GL_DT_SCALE_NV 0x8711
#endif
#ifndef GL_MAGNITUDE_SCALE_NV
#  define GL_MAGNITUDE_SCALE_NV 0x8712
#endif
#ifndef GL_VIBRANCE_SCALE_NV
#  define GL_VIBRANCE_SCALE_NV 0x8713
#endif
#ifndef GL_HI_BIAS_NV
#  define GL_HI_BIAS_NV 0x8714
#endif
#ifndef GL_LO_BIAS_NV
#  define GL_LO_BIAS_NV 0x8715
#endif
#ifndef GL_DS_BIAS_NV
#  define GL_DS_BIAS_NV 0x8716
#endif
#ifndef GL_DT_BIAS_NV
#  define GL_DT_BIAS_NV 0x8717
#endif
#ifndef GL_MAGNITUDE_BIAS_NV
#  define GL_MAGNITUDE_BIAS_NV 0x8718
#endif
#ifndef GL_VIBRANCE_BIAS_NV
#  define GL_VIBRANCE_BIAS_NV 0x8719
#endif
#ifndef GL_TEXTURE_BORDER_VALUES_NV
#  define GL_TEXTURE_BORDER_VALUES_NV 0x871A
#endif
#ifndef GL_TEXTURE_HI_SIZE_NV
#  define GL_TEXTURE_HI_SIZE_NV 0x871B
#endif
#ifndef GL_TEXTURE_LO_SIZE_NV
#  define GL_TEXTURE_LO_SIZE_NV 0x871C
#endif
#ifndef GL_TEXTURE_DS_SIZE_NV
#  define GL_TEXTURE_DS_SIZE_NV 0x871D
#endif
#ifndef GL_TEXTURE_DT_SIZE_NV
#  define GL_TEXTURE_DT_SIZE_NV 0x871E
#endif
#ifndef GL_TEXTURE_MAG_SIZE_NV
#  define GL_TEXTURE_MAG_SIZE_NV 0x871F
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
