
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:36 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_texture_shader3__
#define __GLUX_GL_NV_texture_shader3__

GLUX_NEW_PLUGIN(GL_NV_texture_shader3);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_OFFSET_PROJECTIVE_TEXTURE_2D_NV
#  define GL_OFFSET_PROJECTIVE_TEXTURE_2D_NV 0x8850
#endif
#ifndef GL_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV
#  define GL_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV 0x8851
#endif
#ifndef GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV
#  define GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV 0x8852
#endif
#ifndef GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV
#  define GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV 0x8853
#endif
#ifndef GL_OFFSET_HILO_TEXTURE_2D_NV
#  define GL_OFFSET_HILO_TEXTURE_2D_NV 0x8854
#endif
#ifndef GL_OFFSET_HILO_TEXTURE_RECTANGLE_NV
#  define GL_OFFSET_HILO_TEXTURE_RECTANGLE_NV 0x8855
#endif
#ifndef GL_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV
#  define GL_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV 0x8856
#endif
#ifndef GL_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV
#  define GL_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV 0x8857
#endif
#ifndef GL_DEPENDENT_HILO_TEXTURE_2D_NV
#  define GL_DEPENDENT_HILO_TEXTURE_2D_NV 0x8858
#endif
#ifndef GL_DEPENDENT_RGB_TEXTURE_3D_NV
#  define GL_DEPENDENT_RGB_TEXTURE_3D_NV 0x8859
#endif
#ifndef GL_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV
#  define GL_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV 0x885A
#endif
#ifndef GL_DOT_PRODUCT_PASS_THROUGH_NV
#  define GL_DOT_PRODUCT_PASS_THROUGH_NV 0x885B
#endif
#ifndef GL_DOT_PRODUCT_TEXTURE_1D_NV
#  define GL_DOT_PRODUCT_TEXTURE_1D_NV 0x885C
#endif
#ifndef GL_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV
#  define GL_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV 0x885D
#endif
#ifndef GL_HILO8_NV
#  define GL_HILO8_NV 0x885E
#endif
#ifndef GL_SIGNED_HILO8_NV
#  define GL_SIGNED_HILO8_NV 0x885F
#endif
#ifndef GL_FORCE_BLUE_TO_ONE_NV
#  define GL_FORCE_BLUE_TO_ONE_NV 0x8860
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
