
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ARB_matrix_palette__
#define __GLUX_GL_ARB_matrix_palette__

GLUX_NEW_PLUGIN(GL_ARB_matrix_palette);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_MATRIX_PALETTE_ARB
#  define GL_MATRIX_PALETTE_ARB 0x8840
#endif
#ifndef GL_MAX_MATRIX_PALETTE_STACK_DEPTH_ARB
#  define GL_MAX_MATRIX_PALETTE_STACK_DEPTH_ARB 0x8841
#endif
#ifndef GL_MAX_PALETTE_MATRICES_ARB
#  define GL_MAX_PALETTE_MATRICES_ARB 0x8842
#endif
#ifndef GL_CURRENT_PALETTE_MATRIX_ARB
#  define GL_CURRENT_PALETTE_MATRIX_ARB 0x8843
#endif
#ifndef GL_MATRIX_INDEX_ARRAY_ARB
#  define GL_MATRIX_INDEX_ARRAY_ARB 0x8844
#endif
#ifndef GL_CURRENT_MATRIX_INDEX_ARB
#  define GL_CURRENT_MATRIX_INDEX_ARB 0x8845
#endif
#ifndef GL_MATRIX_INDEX_ARRAY_SIZE_ARB
#  define GL_MATRIX_INDEX_ARRAY_SIZE_ARB 0x8846
#endif
#ifndef GL_MATRIX_INDEX_ARRAY_TYPE_ARB
#  define GL_MATRIX_INDEX_ARRAY_TYPE_ARB 0x8847
#endif
#ifndef GL_MATRIX_INDEX_ARRAY_STRIDE_ARB
#  define GL_MATRIX_INDEX_ARRAY_STRIDE_ARB 0x8848
#endif
#ifndef GL_MATRIX_INDEX_ARRAY_POINTER_ARB
#  define GL_MATRIX_INDEX_ARRAY_POINTER_ARB 0x8849
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glCurrentPaletteMatrixARB
typedef void (APIENTRYP PFNGLUXCURRENTPALETTEMATRIXARBPROC) (GLint index);
#endif
#ifndef __GLUX__GLFCT_glMatrixIndexubvARB
typedef void (APIENTRYP PFNGLUXMATRIXINDEXUBVARBPROC) (GLint size, const GLubyte *indices);
#endif
#ifndef __GLUX__GLFCT_glMatrixIndexusvARB
typedef void (APIENTRYP PFNGLUXMATRIXINDEXUSVARBPROC) (GLint size, const GLushort *indices);
#endif
#ifndef __GLUX__GLFCT_glMatrixIndexuivARB
typedef void (APIENTRYP PFNGLUXMATRIXINDEXUIVARBPROC) (GLint size, const GLuint *indices);
#endif
#ifndef __GLUX__GLFCT_glMatrixIndexPointerARB
typedef void (APIENTRYP PFNGLUXMATRIXINDEXPOINTERARBPROC) (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glCurrentPaletteMatrixARB
extern PFNGLUXCURRENTPALETTEMATRIXARBPROC glCurrentPaletteMatrixARB;
#endif
#ifndef __GLUX__GLFCT_glMatrixIndexubvARB
extern PFNGLUXMATRIXINDEXUBVARBPROC glMatrixIndexubvARB;
#endif
#ifndef __GLUX__GLFCT_glMatrixIndexusvARB
extern PFNGLUXMATRIXINDEXUSVARBPROC glMatrixIndexusvARB;
#endif
#ifndef __GLUX__GLFCT_glMatrixIndexuivARB
extern PFNGLUXMATRIXINDEXUIVARBPROC glMatrixIndexuivARB;
#endif
#ifndef __GLUX__GLFCT_glMatrixIndexPointerARB
extern PFNGLUXMATRIXINDEXPOINTERARBPROC glMatrixIndexPointerARB;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
