// --------------------------------------------------------
#ifdef WIN32

// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_NV_render_depth_texture__
#define __GLUX_WGL_NV_render_depth_texture__

GLUX_NEW_PLUGIN(WGL_NV_render_depth_texture);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef WGL_BIND_TO_TEXTURE_DEPTH_NV
#  define WGL_BIND_TO_TEXTURE_DEPTH_NV 0x20A3
#endif
#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV
#  define WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV 0x20A4
#endif
#ifndef WGL_DEPTH_TEXTURE_FORMAT_NV
#  define WGL_DEPTH_TEXTURE_FORMAT_NV 0x20A5
#endif
#ifndef WGL_TEXTURE_DEPTH_COMPONENT_NV
#  define WGL_TEXTURE_DEPTH_COMPONENT_NV 0x20A6
#endif
#ifndef WGL_DEPTH_COMPONENT_NV
#  define WGL_DEPTH_COMPONENT_NV 0x20A7
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
