
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIS_texture_filter4__
#define __GLUX_GL_SGIS_texture_filter4__

GLUX_NEW_PLUGIN(GL_SGIS_texture_filter4);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_FILTER4_SGIS
#  define GL_FILTER4_SGIS 0x8146
#endif
#ifndef GL_TEXTURE_FILTER4_SIZE_SGIS
#  define GL_TEXTURE_FILTER4_SIZE_SGIS 0x8147
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glGetTexFilterFuncSGIS
typedef void (APIENTRYP PFNGLUXGETTEXFILTERFUNCSGISPROC) (GLenum target, GLenum filter, GLfloat *weights);
#endif
#ifndef __GLUX__GLFCT_glTexFilterFuncSGIS
typedef void (APIENTRYP PFNGLUXTEXFILTERFUNCSGISPROC) (GLenum target, GLenum filter, GLsizei n, const GLfloat *weights);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glGetTexFilterFuncSGIS
extern PFNGLUXGETTEXFILTERFUNCSGISPROC glGetTexFilterFuncSGIS;
#endif
#ifndef __GLUX__GLFCT_glTexFilterFuncSGIS
extern PFNGLUXTEXFILTERFUNCSGISPROC glTexFilterFuncSGIS;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
