
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_copy_depth_to_color__
#define __GLUX_GL_NV_copy_depth_to_color__

GLUX_NEW_PLUGIN(GL_NV_copy_depth_to_color);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_DEPTH_STENCIL_TO_RGBA_NV
#  define GL_DEPTH_STENCIL_TO_RGBA_NV 0x886E
#endif
#ifndef GL_DEPTH_STENCIL_TO_BGRA_NV
#  define GL_DEPTH_STENCIL_TO_BGRA_NV 0x886F
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
