
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIX_sprite__
#define __GLUX_GL_SGIX_sprite__

GLUX_NEW_PLUGIN(GL_SGIX_sprite);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_SPRITE_SGIX
#  define GL_SPRITE_SGIX 0x8148
#endif
#ifndef GL_SPRITE_MODE_SGIX
#  define GL_SPRITE_MODE_SGIX 0x8149
#endif
#ifndef GL_SPRITE_AXIS_SGIX
#  define GL_SPRITE_AXIS_SGIX 0x814A
#endif
#ifndef GL_SPRITE_TRANSLATION_SGIX
#  define GL_SPRITE_TRANSLATION_SGIX 0x814B
#endif
#ifndef GL_SPRITE_AXIAL_SGIX
#  define GL_SPRITE_AXIAL_SGIX 0x814C
#endif
#ifndef GL_SPRITE_OBJECT_ALIGNED_SGIX
#  define GL_SPRITE_OBJECT_ALIGNED_SGIX 0x814D
#endif
#ifndef GL_SPRITE_EYE_ALIGNED_SGIX
#  define GL_SPRITE_EYE_ALIGNED_SGIX 0x814E
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glSpriteParameterfSGIX
typedef void (APIENTRYP PFNGLUXSPRITEPARAMETERFSGIXPROC) (GLenum pname, GLfloat param);
#endif
#ifndef __GLUX__GLFCT_glSpriteParameterfvSGIX
typedef void (APIENTRYP PFNGLUXSPRITEPARAMETERFVSGIXPROC) (GLenum pname, const GLfloat *params);
#endif
#ifndef __GLUX__GLFCT_glSpriteParameteriSGIX
typedef void (APIENTRYP PFNGLUXSPRITEPARAMETERISGIXPROC) (GLenum pname, GLint param);
#endif
#ifndef __GLUX__GLFCT_glSpriteParameterivSGIX
typedef void (APIENTRYP PFNGLUXSPRITEPARAMETERIVSGIXPROC) (GLenum pname, const GLint *params);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glSpriteParameterfSGIX
extern PFNGLUXSPRITEPARAMETERFSGIXPROC glSpriteParameterfSGIX;
#endif
#ifndef __GLUX__GLFCT_glSpriteParameterfvSGIX
extern PFNGLUXSPRITEPARAMETERFVSGIXPROC glSpriteParameterfvSGIX;
#endif
#ifndef __GLUX__GLFCT_glSpriteParameteriSGIX
extern PFNGLUXSPRITEPARAMETERISGIXPROC glSpriteParameteriSGIX;
#endif
#ifndef __GLUX__GLFCT_glSpriteParameterivSGIX
extern PFNGLUXSPRITEPARAMETERIVSGIXPROC glSpriteParameterivSGIX;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
