
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_422_pixels__
#define __GLUX_GL_EXT_422_pixels__

GLUX_NEW_PLUGIN(GL_EXT_422_pixels);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_422_EXT
#  define GL_422_EXT 0x80CC
#endif
#ifndef GL_422_REV_EXT
#  define GL_422_REV_EXT 0x80CD
#endif
#ifndef GL_422_AVERAGE_EXT
#  define GL_422_AVERAGE_EXT 0x80CE
#endif
#ifndef GL_422_REV_AVERAGE_EXT
#  define GL_422_REV_AVERAGE_EXT 0x80CF
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
