
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_OML_resample__
#define __GLUX_GL_OML_resample__

GLUX_NEW_PLUGIN(GL_OML_resample);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_PACK_RESAMPLE_OML
#  define GL_PACK_RESAMPLE_OML 0x8984
#endif
#ifndef GL_UNPACK_RESAMPLE_OML
#  define GL_UNPACK_RESAMPLE_OML 0x8985
#endif
#ifndef GL_RESAMPLE_REPLICATE_OML
#  define GL_RESAMPLE_REPLICATE_OML 0x8986
#endif
#ifndef GL_RESAMPLE_ZERO_FILL_OML
#  define GL_RESAMPLE_ZERO_FILL_OML 0x8987
#endif
#ifndef GL_RESAMPLE_AVERAGE_OML
#  define GL_RESAMPLE_AVERAGE_OML 0x8988
#endif
#ifndef GL_RESAMPLE_DECIMATE_OML
#  define GL_RESAMPLE_DECIMATE_OML 0x8989
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
