
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ARB_fragment_program__
#define __GLUX_GL_ARB_fragment_program__

GLUX_NEW_PLUGIN(GL_ARB_fragment_program);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_FRAGMENT_PROGRAM_ARB
#  define GL_FRAGMENT_PROGRAM_ARB 0x8804
#endif
#ifndef GL_PROGRAM_ALU_INSTRUCTIONS_ARB
#  define GL_PROGRAM_ALU_INSTRUCTIONS_ARB 0x8805
#endif
#ifndef GL_PROGRAM_TEX_INSTRUCTIONS_ARB
#  define GL_PROGRAM_TEX_INSTRUCTIONS_ARB 0x8806
#endif
#ifndef GL_PROGRAM_TEX_INDIRECTIONS_ARB
#  define GL_PROGRAM_TEX_INDIRECTIONS_ARB 0x8807
#endif
#ifndef GL_PROGRAM_NATIVE_ALU_INSTRUCTIONS_ARB
#  define GL_PROGRAM_NATIVE_ALU_INSTRUCTIONS_ARB 0x8808
#endif
#ifndef GL_PROGRAM_NATIVE_TEX_INSTRUCTIONS_ARB
#  define GL_PROGRAM_NATIVE_TEX_INSTRUCTIONS_ARB 0x8809
#endif
#ifndef GL_PROGRAM_NATIVE_TEX_INDIRECTIONS_ARB
#  define GL_PROGRAM_NATIVE_TEX_INDIRECTIONS_ARB 0x880A
#endif
#ifndef GL_MAX_PROGRAM_ALU_INSTRUCTIONS_ARB
#  define GL_MAX_PROGRAM_ALU_INSTRUCTIONS_ARB 0x880B
#endif
#ifndef GL_MAX_PROGRAM_TEX_INSTRUCTIONS_ARB
#  define GL_MAX_PROGRAM_TEX_INSTRUCTIONS_ARB 0x880C
#endif
#ifndef GL_MAX_PROGRAM_TEX_INDIRECTIONS_ARB
#  define GL_MAX_PROGRAM_TEX_INDIRECTIONS_ARB 0x880D
#endif
#ifndef GL_MAX_PROGRAM_NATIVE_ALU_INSTRUCTIONS_ARB
#  define GL_MAX_PROGRAM_NATIVE_ALU_INSTRUCTIONS_ARB 0x880E
#endif
#ifndef GL_MAX_PROGRAM_NATIVE_TEX_INSTRUCTIONS_ARB
#  define GL_MAX_PROGRAM_NATIVE_TEX_INSTRUCTIONS_ARB 0x880F
#endif
#ifndef GL_MAX_PROGRAM_NATIVE_TEX_INDIRECTIONS_ARB
#  define GL_MAX_PROGRAM_NATIVE_TEX_INDIRECTIONS_ARB 0x8810
#endif
#ifndef GL_MAX_TEXTURE_COORDS_ARB
#  define GL_MAX_TEXTURE_COORDS_ARB 0x8871
#endif
#ifndef GL_MAX_TEXTURE_IMAGE_UNITS_ARB
#  define GL_MAX_TEXTURE_IMAGE_UNITS_ARB 0x8872
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
