
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_texture_rectangle__
#define __GLUX_GL_NV_texture_rectangle__

GLUX_NEW_PLUGIN(GL_NV_texture_rectangle);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_TEXTURE_RECTANGLE_NV
#  define GL_TEXTURE_RECTANGLE_NV 0x84F5
#endif
#ifndef GL_TEXTURE_BINDING_RECTANGLE_NV
#  define GL_TEXTURE_BINDING_RECTANGLE_NV 0x84F6
#endif
#ifndef GL_PROXY_TEXTURE_RECTANGLE_NV
#  define GL_PROXY_TEXTURE_RECTANGLE_NV 0x84F7
#endif
#ifndef GL_MAX_RECTANGLE_TEXTURE_SIZE_NV
#  define GL_MAX_RECTANGLE_TEXTURE_SIZE_NV 0x84F8
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
