
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_BUMP_ROT_MATRIX_ATI
#  define GL_BUMP_ROT_MATRIX_ATI 0x8775
#endif
#ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#  define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#endif
#ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#  define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#endif
#ifndef GL_BUMP_TEX_UNITS_ATI
#  define GL_BUMP_TEX_UNITS_ATI 0x8778
#endif
#ifndef GL_DUDV_ATI
#  define GL_DUDV_ATI 0x8779
#endif
#ifndef GL_DU8DV8_ATI
#  define GL_DU8DV8_ATI 0x877A
#endif
#ifndef GL_BUMP_ENVMAP_ATI
#  define GL_BUMP_ENVMAP_ATI 0x877B
#endif
#ifndef GL_BUMP_TARGET_ATI
#  define GL_BUMP_TARGET_ATI 0x877C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
