
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_point_parameters__
#define __GLUX_GL_EXT_point_parameters__

GLUX_NEW_PLUGIN(GL_EXT_point_parameters);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_POINT_SIZE_MIN_EXT
#  define GL_POINT_SIZE_MIN_EXT 0x8126
#endif
#ifndef GL_POINT_SIZE_MAX_EXT
#  define GL_POINT_SIZE_MAX_EXT 0x8127
#endif
#ifndef GL_POINT_FADE_THRESHOLD_SIZE_EXT
#  define GL_POINT_FADE_THRESHOLD_SIZE_EXT 0x8128
#endif
#ifndef GL_DISTANCE_ATTENUATION_EXT
#  define GL_DISTANCE_ATTENUATION_EXT 0x8129
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glPointParameterfEXT
typedef void (APIENTRYP PFNGLUXPOINTPARAMETERFEXTPROC) (GLenum pname, GLfloat param);
#endif
#ifndef __GLUX__GLFCT_glPointParameterfvEXT
typedef void (APIENTRYP PFNGLUXPOINTPARAMETERFVEXTPROC) (GLenum pname, const GLfloat *params);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glPointParameterfEXT
extern PFNGLUXPOINTPARAMETERFEXTPROC glPointParameterfEXT;
#endif
#ifndef __GLUX__GLFCT_glPointParameterfvEXT
extern PFNGLUXPOINTPARAMETERFVEXTPROC glPointParameterfvEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
