
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIX_resample__
#define __GLUX_GL_SGIX_resample__

GLUX_NEW_PLUGIN(GL_SGIX_resample);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_PACK_RESAMPLE_SGIX
#  define GL_PACK_RESAMPLE_SGIX 0x842C
#endif
#ifndef GL_UNPACK_RESAMPLE_SGIX
#  define GL_UNPACK_RESAMPLE_SGIX 0x842D
#endif
#ifndef GL_RESAMPLE_REPLICATE_SGIX
#  define GL_RESAMPLE_REPLICATE_SGIX 0x842E
#endif
#ifndef GL_RESAMPLE_ZERO_FILL_SGIX
#  define GL_RESAMPLE_ZERO_FILL_SGIX 0x842F
#endif
#ifndef GL_RESAMPLE_DECIMATE_SGIX
#  define GL_RESAMPLE_DECIMATE_SGIX 0x8430
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
