
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIS_detail_texture__
#define __GLUX_GL_SGIS_detail_texture__

GLUX_NEW_PLUGIN(GL_SGIS_detail_texture);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_DETAIL_TEXTURE_2D_SGIS
#  define GL_DETAIL_TEXTURE_2D_SGIS 0x8095
#endif
#ifndef GL_DETAIL_TEXTURE_2D_BINDING_SGIS
#  define GL_DETAIL_TEXTURE_2D_BINDING_SGIS 0x8096
#endif
#ifndef GL_LINEAR_DETAIL_SGIS
#  define GL_LINEAR_DETAIL_SGIS 0x8097
#endif
#ifndef GL_LINEAR_DETAIL_ALPHA_SGIS
#  define GL_LINEAR_DETAIL_ALPHA_SGIS 0x8098
#endif
#ifndef GL_LINEAR_DETAIL_COLOR_SGIS
#  define GL_LINEAR_DETAIL_COLOR_SGIS 0x8099
#endif
#ifndef GL_DETAIL_TEXTURE_LEVEL_SGIS
#  define GL_DETAIL_TEXTURE_LEVEL_SGIS 0x809A
#endif
#ifndef GL_DETAIL_TEXTURE_MODE_SGIS
#  define GL_DETAIL_TEXTURE_MODE_SGIS 0x809B
#endif
#ifndef GL_DETAIL_TEXTURE_FUNC_POINTS_SGIS
#  define GL_DETAIL_TEXTURE_FUNC_POINTS_SGIS 0x809C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glDetailTexFuncSGIS
typedef void (APIENTRYP PFNGLUXDETAILTEXFUNCSGISPROC) (GLenum target, GLsizei n, const GLfloat *points);
#endif
#ifndef __GLUX__GLFCT_glGetDetailTexFuncSGIS
typedef void (APIENTRYP PFNGLUXGETDETAILTEXFUNCSGISPROC) (GLenum target, GLfloat *points);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glDetailTexFuncSGIS
extern PFNGLUXDETAILTEXFUNCSGISPROC glDetailTexFuncSGIS;
#endif
#ifndef __GLUX__GLFCT_glGetDetailTexFuncSGIS
extern PFNGLUXGETDETAILTEXFUNCSGISPROC glGetDetailTexFuncSGIS;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
