
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:34 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_S3_s3tc__
#define __GLUX_GL_S3_s3tc__

GLUX_NEW_PLUGIN(GL_S3_s3tc);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_RGB_S3TC
#  define GL_RGB_S3TC 0x83A0
#endif
#ifndef GL_RGB4_S3TC
#  define GL_RGB4_S3TC 0x83A1
#endif
#ifndef GL_RGBA_S3TC
#  define GL_RGBA_S3TC 0x83A2
#endif
#ifndef GL_RGBA4_S3TC
#  define GL_RGBA4_S3TC 0x83A3
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
