
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIS_fog_function__
#define __GLUX_GL_SGIS_fog_function__

GLUX_NEW_PLUGIN(GL_SGIS_fog_function);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_FOG_FUNC_SGIS
#  define GL_FOG_FUNC_SGIS 0x812A
#endif
#ifndef GL_FOG_FUNC_POINTS_SGIS
#  define GL_FOG_FUNC_POINTS_SGIS 0x812B
#endif
#ifndef GL_MAX_FOG_FUNC_POINTS_SGIS
#  define GL_MAX_FOG_FUNC_POINTS_SGIS 0x812C
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glFogFuncSGIS
typedef void (APIENTRYP PFNGLUXFOGFUNCSGISPROC) (GLsizei n, const GLfloat *points);
#endif
#ifndef __GLUX__GLFCT_glGetFogFuncSGIS
typedef void (APIENTRYP PFNGLUXGETFOGFUNCSGISPROC) (GLfloat *points);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glFogFuncSGIS
extern PFNGLUXFOGFUNCSGISPROC glFogFuncSGIS;
#endif
#ifndef __GLUX__GLFCT_glGetFogFuncSGIS
extern PFNGLUXGETFOGFUNCSGISPROC glGetFogFuncSGIS;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
