
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_fence__
#define __GLUX_GL_NV_fence__

GLUX_NEW_PLUGIN(GL_NV_fence);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_ALL_COMPLETED_NV
#  define GL_ALL_COMPLETED_NV 0x84F2
#endif
#ifndef GL_FENCE_STATUS_NV
#  define GL_FENCE_STATUS_NV 0x84F3
#endif
#ifndef GL_FENCE_CONDITION_NV
#  define GL_FENCE_CONDITION_NV 0x84F4
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glDeleteFencesNV
typedef void (APIENTRYP PFNGLUXDELETEFENCESNVPROC) (GLsizei n, const GLuint *fences);
#endif
#ifndef __GLUX__GLFCT_glGenFencesNV
typedef void (APIENTRYP PFNGLUXGENFENCESNVPROC) (GLsizei n, GLuint *fences);
#endif
#ifndef __GLUX__GLFCT_glIsFenceNV
typedef GLboolean (APIENTRYP PFNGLUXISFENCENVPROC) (GLuint fence);
#endif
#ifndef __GLUX__GLFCT_glTestFenceNV
typedef GLboolean (APIENTRYP PFNGLUXTESTFENCENVPROC) (GLuint fence);
#endif
#ifndef __GLUX__GLFCT_glGetFenceivNV
typedef void (APIENTRYP PFNGLUXGETFENCEIVNVPROC) (GLuint fence, GLenum pname, GLint *params);
#endif
#ifndef __GLUX__GLFCT_glFinishFenceNV
typedef void (APIENTRYP PFNGLUXFINISHFENCENVPROC) (GLuint fence);
#endif
#ifndef __GLUX__GLFCT_glSetFenceNV
typedef void (APIENTRYP PFNGLUXSETFENCENVPROC) (GLuint fence, GLenum condition);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glDeleteFencesNV
extern PFNGLUXDELETEFENCESNVPROC glDeleteFencesNV;
#endif
#ifndef __GLUX__GLFCT_glGenFencesNV
extern PFNGLUXGENFENCESNVPROC glGenFencesNV;
#endif
#ifndef __GLUX__GLFCT_glIsFenceNV
extern PFNGLUXISFENCENVPROC glIsFenceNV;
#endif
#ifndef __GLUX__GLFCT_glTestFenceNV
extern PFNGLUXTESTFENCENVPROC glTestFenceNV;
#endif
#ifndef __GLUX__GLFCT_glGetFenceivNV
extern PFNGLUXGETFENCEIVNVPROC glGetFenceivNV;
#endif
#ifndef __GLUX__GLFCT_glFinishFenceNV
extern PFNGLUXFINISHFENCENVPROC glFinishFenceNV;
#endif
#ifndef __GLUX__GLFCT_glSetFenceNV
extern PFNGLUXSETFENCENVPROC glSetFenceNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
