// --------------------------------------------------------
#ifndef WIN32

// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GLX_SGIX_dmbuffer__
#define __GLUX_GLX_SGIX_dmbuffer__

GLUX_NEW_PLUGIN(GLX_SGIX_dmbuffer);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
#ifdef _DM_BUFFER_H_
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GLX_DIGITAL_MEDIA_PBUFFER_SGIX
#  define GLX_DIGITAL_MEDIA_PBUFFER_SGIX 0x8024
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glXAssociateDMPbufferSGIX
typedef Bool (APIENTRYP PFNXGLUXASSOCIATEDMPBUFFERSGIXPROC) (Display *dpy, GLXPbufferSGIX pbuffer, DMparams *params, DMbuffer dmbuffer);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glXAssociateDMPbufferSGIX
extern PFNXGLUXASSOCIATEDMPBUFFERSGIXPROC glXAssociateDMPbufferSGIX;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
