
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_subtexture__
#define __GLUX_GL_EXT_subtexture__

GLUX_NEW_PLUGIN(GL_EXT_subtexture);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexSubImage1DEXT
typedef void (APIENTRYP PFNGLUXTEXSUBIMAGE1DEXTPROC) (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
#endif
#ifndef __GLUX__GLFCT_glTexSubImage2DEXT
typedef void (APIENTRYP PFNGLUXTEXSUBIMAGE2DEXTPROC) (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexSubImage1DEXT
extern PFNGLUXTEXSUBIMAGE1DEXTPROC glTexSubImage1DEXT;
#endif
#ifndef __GLUX__GLFCT_glTexSubImage2DEXT
extern PFNGLUXTEXSUBIMAGE2DEXTPROC glTexSubImage2DEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
