
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:34 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_texture_mirror_clamp__
#define __GLUX_GL_EXT_texture_mirror_clamp__

GLUX_NEW_PLUGIN(GL_EXT_texture_mirror_clamp);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_MIRROR_CLAMP_EXT
#  define GL_MIRROR_CLAMP_EXT 0x8742
#endif
#ifndef GL_MIRROR_CLAMP_TO_EDGE_EXT
#  define GL_MIRROR_CLAMP_TO_EDGE_EXT 0x8743
#endif
#ifndef GL_MIRROR_CLAMP_TO_BORDER_EXT
#  define GL_MIRROR_CLAMP_TO_BORDER_EXT 0x8912
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
