
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:36 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIS_texture_lod__
#define __GLUX_GL_SGIS_texture_lod__

GLUX_NEW_PLUGIN(GL_SGIS_texture_lod);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_TEXTURE_MIN_LOD_SGIS
#  define GL_TEXTURE_MIN_LOD_SGIS 0x813A
#endif
#ifndef GL_TEXTURE_MAX_LOD_SGIS
#  define GL_TEXTURE_MAX_LOD_SGIS 0x813B
#endif
#ifndef GL_TEXTURE_BASE_LEVEL_SGIS
#  define GL_TEXTURE_BASE_LEVEL_SGIS 0x813C
#endif
#ifndef GL_TEXTURE_MAX_LEVEL_SGIS
#  define GL_TEXTURE_MAX_LEVEL_SGIS 0x813D
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
