
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_INGR_color_clamp__
#define __GLUX_GL_INGR_color_clamp__

GLUX_NEW_PLUGIN(GL_INGR_color_clamp);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_RED_MIN_CLAMP_INGR
#  define GL_RED_MIN_CLAMP_INGR 0x8560
#endif
#ifndef GL_GREEN_MIN_CLAMP_INGR
#  define GL_GREEN_MIN_CLAMP_INGR 0x8561
#endif
#ifndef GL_BLUE_MIN_CLAMP_INGR
#  define GL_BLUE_MIN_CLAMP_INGR 0x8562
#endif
#ifndef GL_ALPHA_MIN_CLAMP_INGR
#  define GL_ALPHA_MIN_CLAMP_INGR 0x8563
#endif
#ifndef GL_RED_MAX_CLAMP_INGR
#  define GL_RED_MAX_CLAMP_INGR 0x8564
#endif
#ifndef GL_GREEN_MAX_CLAMP_INGR
#  define GL_GREEN_MAX_CLAMP_INGR 0x8565
#endif
#ifndef GL_BLUE_MAX_CLAMP_INGR
#  define GL_BLUE_MAX_CLAMP_INGR 0x8566
#endif
#ifndef GL_ALPHA_MAX_CLAMP_INGR
#  define GL_ALPHA_MAX_CLAMP_INGR 0x8567
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
