
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_texture_float__
#define __GLUX_GL_ATI_texture_float__

GLUX_NEW_PLUGIN(GL_ATI_texture_float);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_RGBA_FLOAT32_ATI
#  define GL_RGBA_FLOAT32_ATI 0x8814
#endif
#ifndef GL_RGB_FLOAT32_ATI
#  define GL_RGB_FLOAT32_ATI 0x8815
#endif
#ifndef GL_ALPHA_FLOAT32_ATI
#  define GL_ALPHA_FLOAT32_ATI 0x8816
#endif
#ifndef GL_INTENSITY_FLOAT32_ATI
#  define GL_INTENSITY_FLOAT32_ATI 0x8817
#endif
#ifndef GL_LUMINANCE_FLOAT32_ATI
#  define GL_LUMINANCE_FLOAT32_ATI 0x8818
#endif
#ifndef GL_LUMINANCE_ALPHA_FLOAT32_ATI
#  define GL_LUMINANCE_ALPHA_FLOAT32_ATI 0x8819
#endif
#ifndef GL_RGBA_FLOAT16_ATI
#  define GL_RGBA_FLOAT16_ATI 0x881A
#endif
#ifndef GL_RGB_FLOAT16_ATI
#  define GL_RGB_FLOAT16_ATI 0x881B
#endif
#ifndef GL_ALPHA_FLOAT16_ATI
#  define GL_ALPHA_FLOAT16_ATI 0x881C
#endif
#ifndef GL_INTENSITY_FLOAT16_ATI
#  define GL_INTENSITY_FLOAT16_ATI 0x881D
#endif
#ifndef GL_LUMINANCE_FLOAT16_ATI
#  define GL_LUMINANCE_FLOAT16_ATI 0x881E
#endif
#ifndef GL_LUMINANCE_ALPHA_FLOAT16_ATI
#  define GL_LUMINANCE_ALPHA_FLOAT16_ATI 0x881F
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
