
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIS_sharpen_texture__
#define __GLUX_GL_SGIS_sharpen_texture__

GLUX_NEW_PLUGIN(GL_SGIS_sharpen_texture);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_LINEAR_SHARPEN_SGIS
#  define GL_LINEAR_SHARPEN_SGIS 0x80AD
#endif
#ifndef GL_LINEAR_SHARPEN_ALPHA_SGIS
#  define GL_LINEAR_SHARPEN_ALPHA_SGIS 0x80AE
#endif
#ifndef GL_LINEAR_SHARPEN_COLOR_SGIS
#  define GL_LINEAR_SHARPEN_COLOR_SGIS 0x80AF
#endif
#ifndef GL_SHARPEN_TEXTURE_FUNC_POINTS_SGIS
#  define GL_SHARPEN_TEXTURE_FUNC_POINTS_SGIS 0x80B0
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glSharpenTexFuncSGIS
typedef void (APIENTRYP PFNGLUXSHARPENTEXFUNCSGISPROC) (GLenum target, GLsizei n, const GLfloat *points);
#endif
#ifndef __GLUX__GLFCT_glGetSharpenTexFuncSGIS
typedef void (APIENTRYP PFNGLUXGETSHARPENTEXFUNCSGISPROC) (GLenum target, GLfloat *points);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glSharpenTexFuncSGIS
extern PFNGLUXSHARPENTEXFUNCSGISPROC glSharpenTexFuncSGIS;
#endif
#ifndef __GLUX__GLFCT_glGetSharpenTexFuncSGIS
extern PFNGLUXGETSHARPENTEXFUNCSGISPROC glGetSharpenTexFuncSGIS;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
