
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIS_generate_mipmap__
#define __GLUX_GL_SGIS_generate_mipmap__

GLUX_NEW_PLUGIN(GL_SGIS_generate_mipmap);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_GENERATE_MIPMAP_SGIS
#  define GL_GENERATE_MIPMAP_SGIS 0x8191
#endif
#ifndef GL_GENERATE_MIPMAP_HINT_SGIS
#  define GL_GENERATE_MIPMAP_HINT_SGIS 0x8192
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
