
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIX_subsample__
#define __GLUX_GL_SGIX_subsample__

GLUX_NEW_PLUGIN(GL_SGIX_subsample);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_PACK_SUBSAMPLE_RATE_SGIX
#  define GL_PACK_SUBSAMPLE_RATE_SGIX 0x85A0
#endif
#ifndef GL_UNPACK_SUBSAMPLE_RATE_SGIX
#  define GL_UNPACK_SUBSAMPLE_RATE_SGIX 0x85A1
#endif
#ifndef GL_PIXEL_SUBSAMPLE_4444_SGIX
#  define GL_PIXEL_SUBSAMPLE_4444_SGIX 0x85A2
#endif
#ifndef GL_PIXEL_SUBSAMPLE_2424_SGIX
#  define GL_PIXEL_SUBSAMPLE_2424_SGIX 0x85A3
#endif
#ifndef GL_PIXEL_SUBSAMPLE_4242_SGIX
#  define GL_PIXEL_SUBSAMPLE_4242_SGIX 0x85A4
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
