
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_separate_stencil__
#define __GLUX_GL_ATI_separate_stencil__

GLUX_NEW_PLUGIN(GL_ATI_separate_stencil);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_STENCIL_BACK_FUNC_ATI
#  define GL_STENCIL_BACK_FUNC_ATI 0x8800
#endif
#ifndef GL_STENCIL_BACK_FAIL_ATI
#  define GL_STENCIL_BACK_FAIL_ATI 0x8801
#endif
#ifndef GL_STENCIL_BACK_PASS_DEPTH_FAIL_ATI
#  define GL_STENCIL_BACK_PASS_DEPTH_FAIL_ATI 0x8802
#endif
#ifndef GL_STENCIL_BACK_PASS_DEPTH_PASS_ATI
#  define GL_STENCIL_BACK_PASS_DEPTH_PASS_ATI 0x8803
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glStencilOpSeparateATI
typedef void (APIENTRYP PFNGLUXSTENCILOPSEPARATEATIPROC) (GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
#endif
#ifndef __GLUX__GLFCT_glStencilFuncSeparateATI
typedef void (APIENTRYP PFNGLUXSTENCILFUNCSEPARATEATIPROC) (GLenum frontfunc, GLenum backfunc, GLint ref, GLuint mask);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glStencilOpSeparateATI
extern PFNGLUXSTENCILOPSEPARATEATIPROC glStencilOpSeparateATI;
#endif
#ifndef __GLUX__GLFCT_glStencilFuncSeparateATI
extern PFNGLUXSTENCILFUNCSEPARATEATIPROC glStencilFuncSeparateATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
