// --------------------------------------------------------
#ifdef WIN32

// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:36 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_ARB_make_current_read__
#define __GLUX_WGL_ARB_make_current_read__

GLUX_NEW_PLUGIN(WGL_ARB_make_current_read);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_wglMakeContextCurrentARB
typedef BOOL (APIENTRYP PFNWGLUXMAKECONTEXTCURRENTARBPROC) (HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
#endif
#ifndef __GLUX__GLFCT_wglGetCurrentReadDCARB
typedef HDC (APIENTRYP PFNWGLUXGETCURRENTREADDCARBPROC) (void);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_wglMakeContextCurrentARB
extern PFNWGLUXMAKECONTEXTCURRENTARBPROC wglMakeContextCurrentARB;
#endif
#ifndef __GLUX__GLFCT_wglGetCurrentReadDCARB
extern PFNWGLUXGETCURRENTREADDCARBPROC wglGetCurrentReadDCARB;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
