
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:36 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIX_polynomial_ffd__
#define __GLUX_GL_SGIX_polynomial_ffd__

GLUX_NEW_PLUGIN(GL_SGIX_polynomial_ffd);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_GEOMETRY_DEFORMATION_SGIX
#  define GL_GEOMETRY_DEFORMATION_SGIX 0x8194
#endif
#ifndef GL_TEXTURE_DEFORMATION_SGIX
#  define GL_TEXTURE_DEFORMATION_SGIX 0x8195
#endif
#ifndef GL_DEFORMATIONS_MASK_SGIX
#  define GL_DEFORMATIONS_MASK_SGIX 0x8196
#endif
#ifndef GL_MAX_DEFORMATION_ORDER_SGIX
#  define GL_MAX_DEFORMATION_ORDER_SGIX 0x8197
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glDeformationMap3dSGIX
typedef void (APIENTRYP PFNGLUXDEFORMATIONMAP3DSGIXPROC) (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, GLdouble w1, GLdouble w2, GLint wstride, GLint worder, const GLdouble *points);
#endif
#ifndef __GLUX__GLFCT_glDeformationMap3fSGIX
typedef void (APIENTRYP PFNGLUXDEFORMATIONMAP3FSGIXPROC) (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, GLfloat w1, GLfloat w2, GLint wstride, GLint worder, const GLfloat *points);
#endif
#ifndef __GLUX__GLFCT_glDeformSGIX
typedef void (APIENTRYP PFNGLUXDEFORMSGIXPROC) (GLbitfield mask);
#endif
#ifndef __GLUX__GLFCT_glLoadIdentityDeformationMapSGIX
typedef void (APIENTRYP PFNGLUXLOADIDENTITYDEFORMATIONMAPSGIXPROC) (GLbitfield mask);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glDeformationMap3dSGIX
extern PFNGLUXDEFORMATIONMAP3DSGIXPROC glDeformationMap3dSGIX;
#endif
#ifndef __GLUX__GLFCT_glDeformationMap3fSGIX
extern PFNGLUXDEFORMATIONMAP3FSGIXPROC glDeformationMap3fSGIX;
#endif
#ifndef __GLUX__GLFCT_glDeformSGIX
extern PFNGLUXDEFORMSGIXPROC glDeformSGIX;
#endif
#ifndef __GLUX__GLFCT_glLoadIdentityDeformationMapSGIX
extern PFNGLUXLOADIDENTITYDEFORMATIONMAPSGIXPROC glLoadIdentityDeformationMapSGIX;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
