
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_texture_mirror_once__
#define __GLUX_GL_ATI_texture_mirror_once__

GLUX_NEW_PLUGIN(GL_ATI_texture_mirror_once);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_MIRROR_CLAMP_ATI
#  define GL_MIRROR_CLAMP_ATI 0x8742
#endif
#ifndef GL_MIRROR_CLAMP_TO_EDGE_ATI
#  define GL_MIRROR_CLAMP_TO_EDGE_ATI 0x8743
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
