
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:35 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGI_texture_color_table__
#define __GLUX_GL_SGI_texture_color_table__

GLUX_NEW_PLUGIN(GL_SGI_texture_color_table);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_TEXTURE_COLOR_TABLE_SGI
#  define GL_TEXTURE_COLOR_TABLE_SGI 0x80BC
#endif
#ifndef GL_PROXY_TEXTURE_COLOR_TABLE_SGI
#  define GL_PROXY_TEXTURE_COLOR_TABLE_SGI 0x80BD
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
