
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:36 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_texture_env_dot3__
#define __GLUX_GL_EXT_texture_env_dot3__

GLUX_NEW_PLUGIN(GL_EXT_texture_env_dot3);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_DOT3_RGB_EXT
#  define GL_DOT3_RGB_EXT 0x8740
#endif
#ifndef GL_DOT3_RGBA_EXT
#  define GL_DOT3_RGBA_EXT 0x8741
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
