
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIX_shadow__
#define __GLUX_GL_SGIX_shadow__

GLUX_NEW_PLUGIN(GL_SGIX_shadow);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_TEXTURE_COMPARE_SGIX
#  define GL_TEXTURE_COMPARE_SGIX 0x819A
#endif
#ifndef GL_TEXTURE_COMPARE_OPERATOR_SGIX
#  define GL_TEXTURE_COMPARE_OPERATOR_SGIX 0x819B
#endif
#ifndef GL_TEXTURE_LEQUAL_R_SGIX
#  define GL_TEXTURE_LEQUAL_R_SGIX 0x819C
#endif
#ifndef GL_TEXTURE_GEQUAL_R_SGIX
#  define GL_TEXTURE_GEQUAL_R_SGIX 0x819D
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
