// --------------------------------------------------------
#ifdef WIN32

// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_I3D_digital_video_control__
#define __GLUX_WGL_I3D_digital_video_control__

GLUX_NEW_PLUGIN(WGL_I3D_digital_video_control);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D
#  define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D 0x2050
#endif
#ifndef WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D
#  define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D 0x2051
#endif
#ifndef WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D
#  define WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D 0x2052
#endif
#ifndef WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D
#  define WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D 0x2053
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_wglGetDigitalVideoParametersI3D
typedef BOOL (APIENTRYP PFNWGLUXGETDIGITALVIDEOPARAMETERSI3DPROC) (HDC hDC, int iAttribute, int *piValue);
#endif
#ifndef __GLUX__GLFCT_wglSetDigitalVideoParametersI3D
typedef BOOL (APIENTRYP PFNWGLUXSETDIGITALVIDEOPARAMETERSI3DPROC) (HDC hDC, int iAttribute, const int *piValue);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_wglGetDigitalVideoParametersI3D
extern PFNWGLUXGETDIGITALVIDEOPARAMETERSI3DPROC wglGetDigitalVideoParametersI3D;
#endif
#ifndef __GLUX__GLFCT_wglSetDigitalVideoParametersI3D
extern PFNWGLUXSETDIGITALVIDEOPARAMETERSI3DPROC wglSetDigitalVideoParametersI3D;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
