
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_point_sprite__
#define __GLUX_GL_NV_point_sprite__

GLUX_NEW_PLUGIN(GL_NV_point_sprite);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_POINT_SPRITE_NV
#  define GL_POINT_SPRITE_NV 0x8861
#endif
#ifndef GL_COORD_REPLACE_NV
#  define GL_COORD_REPLACE_NV 0x8862
#endif
#ifndef GL_POINT_SPRITE_R_MODE_NV
#  define GL_POINT_SPRITE_R_MODE_NV 0x8863
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glPointParameteriNV
typedef void (APIENTRYP PFNGLUXPOINTPARAMETERINVPROC) (GLenum pname, GLint param);
#endif
#ifndef __GLUX__GLFCT_glPointParameterivNV
typedef void (APIENTRYP PFNGLUXPOINTPARAMETERIVNVPROC) (GLenum pname, const GLint *params);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glPointParameteriNV
extern PFNGLUXPOINTPARAMETERINVPROC glPointParameteriNV;
#endif
#ifndef __GLUX__GLFCT_glPointParameterivNV
extern PFNGLUXPOINTPARAMETERIVNVPROC glPointParameterivNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
