// --------------------------------------------------------
#ifdef WIN32

// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:33 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_NV_float_buffer__
#define __GLUX_WGL_NV_float_buffer__

GLUX_NEW_PLUGIN(WGL_NV_float_buffer);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef WGL_FLOAT_COMPONENTS_NV
#  define WGL_FLOAT_COMPONENTS_NV 0x20B0
#endif
#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV
#  define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV 0x20B1
#endif
#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV
#  define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV 0x20B2
#endif
#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV
#  define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV 0x20B3
#endif
#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV
#  define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV 0x20B4
#endif
#ifndef WGL_TEXTURE_FLOAT_R_NV
#  define WGL_TEXTURE_FLOAT_R_NV 0x20B5
#endif
#ifndef WGL_TEXTURE_FLOAT_RG_NV
#  define WGL_TEXTURE_FLOAT_RG_NV 0x20B6
#endif
#ifndef WGL_TEXTURE_FLOAT_RGB_NV
#  define WGL_TEXTURE_FLOAT_RGB_NV 0x20B7
#endif
#ifndef WGL_TEXTURE_FLOAT_RGBA_NV
#  define WGL_TEXTURE_FLOAT_RGBA_NV 0x20B8
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
