
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:36 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGI_depth_pass_instrument__
#define __GLUX_GL_SGI_depth_pass_instrument__

GLUX_NEW_PLUGIN(GL_SGI_depth_pass_instrument);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_DEPTH_PASS_INSTRUMENT_SGIX
#  define GL_DEPTH_PASS_INSTRUMENT_SGIX 0x8310
#endif
#ifndef GL_DEPTH_PASS_INSTRUMENT_COUNTERS_SGIX
#  define GL_DEPTH_PASS_INSTRUMENT_COUNTERS_SGIX 0x8311
#endif
#ifndef GL_DEPTH_PASS_INSTRUMENT_MAX_SGIX
#  define GL_DEPTH_PASS_INSTRUMENT_MAX_SGIX 0x8312
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
