
// --------------------------------------------------------
// Generated by glux perl script (Wed Mar 31 17:19:32 2004)
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#include "glux_no_redefine.h"
#include "glux_ext_defs.h"
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_INTEL_parallel_arrays__
#define __GLUX_GL_INTEL_parallel_arrays__

GLUX_NEW_PLUGIN(GL_INTEL_parallel_arrays);
// --------------------------------------------------------
//           Extension conditions
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifndef GL_PARALLEL_ARRAYS_INTEL
#  define GL_PARALLEL_ARRAYS_INTEL 0x83F4
#endif
#ifndef GL_VERTEX_ARRAY_PARALLEL_POINTERS_INTEL
#  define GL_VERTEX_ARRAY_PARALLEL_POINTERS_INTEL 0x83F5
#endif
#ifndef GL_NORMAL_ARRAY_PARALLEL_POINTERS_INTEL
#  define GL_NORMAL_ARRAY_PARALLEL_POINTERS_INTEL 0x83F6
#endif
#ifndef GL_COLOR_ARRAY_PARALLEL_POINTERS_INTEL
#  define GL_COLOR_ARRAY_PARALLEL_POINTERS_INTEL 0x83F7
#endif
#ifndef GL_TEXTURE_COORD_ARRAY_PARALLEL_POINTERS_INTEL
#  define GL_TEXTURE_COORD_ARRAY_PARALLEL_POINTERS_INTEL 0x83F8
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexPointervINTEL
typedef void (APIENTRYP PFNGLUXVERTEXPOINTERVINTELPROC) (GLint size, GLenum type, const GLvoid* *pointer);
#endif
#ifndef __GLUX__GLFCT_glNormalPointervINTEL
typedef void (APIENTRYP PFNGLUXNORMALPOINTERVINTELPROC) (GLenum type, const GLvoid* *pointer);
#endif
#ifndef __GLUX__GLFCT_glColorPointervINTEL
typedef void (APIENTRYP PFNGLUXCOLORPOINTERVINTELPROC) (GLint size, GLenum type, const GLvoid* *pointer);
#endif
#ifndef __GLUX__GLFCT_glTexCoordPointervINTEL
typedef void (APIENTRYP PFNGLUXTEXCOORDPOINTERVINTELPROC) (GLint size, GLenum type, const GLvoid* *pointer);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexPointervINTEL
extern PFNGLUXVERTEXPOINTERVINTELPROC glVertexPointervINTEL;
#endif
#ifndef __GLUX__GLFCT_glNormalPointervINTEL
extern PFNGLUXNORMALPOINTERVINTELPROC glNormalPointervINTEL;
#endif
#ifndef __GLUX__GLFCT_glColorPointervINTEL
extern PFNGLUXCOLORPOINTERVINTELPROC glColorPointervINTEL;
#endif
#ifndef __GLUX__GLFCT_glTexCoordPointervINTEL
extern PFNGLUXTEXCOORDPOINTERVINTELPROC glTexCoordPointervINTEL;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
