// C4D-DialogResource
DIALOG DLG_FXRENDERER
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC18; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP IDC_RENDER
    {
      NAME IDS_STATIC3; ALIGN_TOP; FIT_H; SCALE_H; 
      BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 1;
      SPACE 4, 4;
      
      BUTTON IDC_RENDER_WINDOW { NAME IDS_BUTTON2; ALIGN_TOP; FIT_H; SCALE_H; }
      CHECKBOX IDC_RENDER_RT { NAME IDS_CHECK1; ALIGN_TOP; ALIGN_LEFT;  }
      BUTTON IDC_RENDER_FILE { NAME IDS_BUTTON; ALIGN_TOP; FIT_H; SCALE_H; }
    }
    GROUP IDC_ANTIALIAS
    {
      NAME IDS_STATIC1; ALIGN_TOP; FIT_H; 
      BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 1;
      SPACE 4, 4;
      
      RADIOGROUP IDC_ANTIALIASING_RADIO
      {
        NAME IDS_STATIC2; ALIGN_TOP; FIT_H; 
        BORDERSIZE 4, 4, 4, 4; 
        SPACE 4, 4;
        
        RADIOGADGET IDC_AA0 { NAME IDS_RADIO; ALIGN_TOP; ALIGN_LEFT;  }
        RADIOGADGET IDC_AA1 { NAME IDS_RADIO1; ALIGN_TOP; ALIGN_LEFT;  }
        RADIOGADGET IDC_AA2 { NAME IDS_RADIO2; ALIGN_TOP; ALIGN_LEFT;  }
      }
    }
    GROUP IDC_MAPSIZE
    {
      NAME IDS_STATIC23; ALIGN_TOP; FIT_H; 
      BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 1;
      SPACE 4, 4;
      
      RADIOGROUP IDC_MAPSIZE_RADIO
      {
        NAME IDS_STATIC24; ALIGN_TOP; FIT_H; 
        BORDERSIZE 4, 4, 4, 4; 
        SPACE 4, 4;
        
        RADIOGADGET IDC_MS64 { NAME IDS_MS_RADIO64; ALIGN_TOP; ALIGN_LEFT;  }
        RADIOGADGET IDC_MS128 { NAME IDS_MS_RADIO128; ALIGN_TOP; ALIGN_LEFT;  }
        RADIOGADGET IDC_MS256 { NAME IDS_MS_RADIO256; ALIGN_TOP; ALIGN_LEFT;  }
        RADIOGADGET IDC_MS512 { NAME IDS_MS_RADIO512; ALIGN_TOP; ALIGN_LEFT;  }
        RADIOGADGET IDC_MS1024 { NAME IDS_MS_RADIO1024; ALIGN_TOP; ALIGN_LEFT;  }
      }
    }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC22; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC10; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC25; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC11; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC12; CENTER_V; ALIGN_LEFT; }
  }
}