//
// Includes
//

#include "wglPBufferARB.h"

#include "wglExtensionsStringARB.h"


PFNWGLCREATEPBUFFERARBPROC      wglCreatePbufferARB;
PFNWGLGETPBUFFERDCARBPROC       wglGetPbufferDCARB;
PFNWGLRELEASEPBUFFERDCARBPROC   wglReleasePbufferDCARB;
PFNWGLDESTROYPBUFFERARBPROC     wglDestroyPbufferARB;
PFNWGLQUERYPBUFFERARBPROC       wglQueryPbufferARB;


void initPBufferARB(HDC hDC)
{
    ASSERT_EXTENSION_SUPPORT(WGL_ARB_pbuffer);

    INIT_FUNCT_PTR(wglCreatePbufferARB, PFNWGLCREATEPBUFFERARBPROC);
    INIT_FUNCT_PTR(wglGetPbufferDCARB, PFNWGLGETPBUFFERDCARBPROC);
    INIT_FUNCT_PTR(wglReleasePbufferDCARB, PFNWGLRELEASEPBUFFERDCARBPROC);
    INIT_FUNCT_PTR(wglDestroyPbufferARB, PFNWGLDESTROYPBUFFERARBPROC);
    INIT_FUNCT_PTR(wglQueryPbufferARB, PFNWGLQUERYPBUFFERARBPROC);
}
