ROOTDIR = ../..
STATIC_LIBRARY = brccsplitting
FILES = splittree splitnode splitbuilder splittraversal splittypes splitcompiler splitcompilercg splitcompilerhlsl splitdominator splitconfiguration splitnodeset

include ../../common.mk
